### ISSUE TITLE
POISON_MESSAGE_HANDLING (STATUS = OFF)

### ISSUE THREAD

**Issue by OpenSpacesAndPlaces** [christiandelbianco/monitor-table-change-with-sqltabledependency#10]
When creating a queue in MSSQL2008 (non-r2), that parameter is causing an error:

SqlException: Incorrect syntax near 'POISON_MESSAGE_HANDLING'.
Incorrect syntax near ')'.

From a little bit of digging it looks like that was not added until R2.

**Comment by christiandelbianco** [comment]
Hi...
SqlTableDependecy was tested starting from MS SQL 2008 R2.
SqlServer Lower version are not supported.
