### ISSUE TITLE
Entity is returning Empty strings as NULL

### ISSUE THREAD

**Issue by c-herberg** [christiandelbianco/monitor-table-change-with-sqltabledependency#101]
I'm running into an issue where if I have a VARCHAR field and am changing the value to be an empty string the change event is returning that column's value as null. I thought at first that maybe my model name for mapping was off but if I update the column value to "Test" it's fine but if I change it to "" it returns null. This is happening for both NULL and NOT NULL VARCHAR fields

I have tried multiple tables and multiple versions of SQL and I get the same issue so I'm running out of ideas

I apologize in advance if this is an optional parameter that I'm able to specify somewhere

Thanks!

**Comment by christiandelbianco** [comment]
Hi.
For my understanding, you would like to have Empty string instead of null when an UPDATE set = '' is executed on database table?

**Comment by c-herberg** [comment]
Yes that is correct, I would expect UPDATE set = '' to return empty string and UPDATE set = NULL to return null

**Comment by christiandelbianco** [comment]
Issue Reproduced => Bug opened.

**Comment by christiandelbianco** [comment]
Hi. After some analysis, i realized that to change this behavior the amount of work is really huge.
Considering that your is an edge case and that SqlTableDependency is a free component, i have decided to leave as it is. Sorry. I hope you understand.

**Comment by christiandelbianco** [comment]
**Everything is just according the ANSI standard**. 

Please check: [How SQL Server Compares Strings with Trailing Spaces](https://support.microsoft.com/en-us/help/316626/inf-how-sql-server-compares-strings-with-trailing-spaces)
