### ISSUE TITLE
SqlTableDependency on Sql 2016

### ISSUE THREAD

**Issue by leon289** [christiandelbianco/monitor-table-change-with-sqltabledependency#102]
Hi , i'm trying to use SqlTableDependency with a SQL 2016 database and i'm having some issue ,
every time that the **Start()** method is called i receive this message :
![image](https://user-images.githubusercontent.com/28443607/47092112-8c587e00-d226-11e8-8a98-1749138a10b7.png)

I tried to use the same database on a Sql 2012  instance and it work but not with any sql 2016 istance
Below the sql 2016 that i used : 
>13.0.4001 (SQLEXPRESS) 
>13.0.4224 (SQL DEVELOPER)

Both are in different  machines and both gave the same error.

Is there a way to solve it ? 
Thanks in advance!

**Comment by leon289** [comment]
My bad , just found a database trigger that was interfering with the table trigger creation .
Issue can be closed

**Comment by christiandelbianco** [comment]
Thank for informing about
