### ISSUE TITLE
Delete al elements created by sqlTabledependency

### ISSUE THREAD

**Issue by gaznapirotuercas** [christiandelbianco/monitor-table-change-with-sqltabledependency#103]
hi, i am using your code to test a web application and i must to say it's great!! it's work perfectly but when i decide to stop monitoring all trigger createn by sqlTabledependency does not deleted, my question is there are any method to delete all dependencies when stop monitoring?

![sqltdependency](https://user-images.githubusercontent.com/20656701/47457872-1b1c4c00-d78d-11e8-8fb7-bfc39d2a3bf7.PNG)
![image](https://user-images.githubusercontent.com/20656701/47457994-6171ab00-d78d-11e8-9d03-2605ba7c772d.png)
![image](https://user-images.githubusercontent.com/20656701/47458010-6d5d6d00-d78d-11e8-937e-183e08997ba4.png)

I'm attaching some pictures of all elements created by monitoring table i'm trying to delete all elements when i close my console application that monitoring the table.

**Comment by gaznapirotuercas** [comment]
thanks for your answer!! my interface problem was to have refreshed the sql manager studio to see what if they were erasing !!

**Comment by christiandelbianco** [comment]
Good. Can you close this bu

**Comment by christiandelbianco** [comment]
Can you close the bug you opened?

**Comment by gaznapirotuercas** [comment]
yes!

**Comment by gaznapirotuercas** [comment]
how to close?
