### ISSUE TITLE
CreateSqlServerDatabaseObjects - create Trigger - not OLTP ready

### ISSUE THREAD

**Issue by Breiti1183** [christiandelbianco/monitor-table-change-with-sqltabledependency#104]
the method CreateSqlServerDatabaseObjects do not work for OLTP Tables. The create of the TRIGGER did not work! 
Any idea how it can be made working? The TSQL cmd BEGIN DIALOG is not a valid one for natice compiled sp...
regards

**Comment by christiandelbianco** [comment]
Hi. In the documentation there is always reported database table - not In-Memory OLTP table.
SqlTableDependency works only for traditional disk-based tables.
