### ISSUE TITLE
SqlTableDependency can't install on my solution

### ISSUE THREAD

**Issue by kronikles** [christiandelbianco/monitor-table-change-with-sqltabledependency#106]
Hi Good day,

I was trying to add this in my solution. But I can't be installed because of my Automapper. Can you help me about this without uninstalling my Automapper? Please see image below .

![image](https://user-images.githubusercontent.com/17491778/48879562-41dea880-ee47-11e8-81fc-89db30fcc4f5.png)

**Comment by christiandelbianco** [comment]
Hi, unfortunately i have no idea.

**Comment by christiandelbianco** [comment]
Also, because this error is not SqlTableDependency related, i will close the bug.
