### ISSUE TITLE
Sql User group

### ISSUE THREAD

**Issue by Primabase** [christiandelbianco/monitor-table-change-with-sqltabledependency#107]
The user used in the connection string must be in db_owner group?

Thank you!

**Comment by christiandelbianco** [comment]
In case the user specified in the connection string is not database Administrator, db owner or neither has db_owner role, please make sure to GRANT the following permissions to your login user:

    ALTER
    CONNECT
    CONTROL
    CREATE CONTRACT
    CREATE MESSAGE TYPE
    CREATE PROCEDURE
    CREATE QUEUE
    CREATE SERVICE
    EXECUTE
    SELECT
    SUBSCRIBE QUERY NOTIFICATIONS
    VIEW DATABASE STATE
    VIEW DEFINITION
