### ISSUE TITLE
Max Number of SqlTableDependencies

### ISSUE THREAD

**Issue by blenet** [christiandelbianco/monitor-table-change-with-sqltabledependency#109]
Hi,

i am implementing a multi client wpf application, means multiple clients have access to the same database and need information if another client changes something in the database. Therefore i found your project to get notifications when an update in a database happens. Right now i only tested it with one client which works great so far. Now i have some concers what happens when for example ~10 clients listen to db changes using sqltabledependency. Is it possible to have more clients listening for changes or should there only be one, i am asking because i see a lot more service-broker elements in sql management studio when i start my client multiple times.
Thanks!

**Comment by christiandelbianco** [comment]
Hi,
if you need more clients listening for changes, you must implement some common service that wrap SqlTableDependency and broadcast notification to all clients. Please have a look at the following example: 

https://github.com/christiandelbianco/monitor-table-change-with-WPF-WCF-sqltabledependency-example 

Regards
