### ISSUE TITLE
Enum causing issues

### ISSUE THREAD

**Issue by nimeshdhruve** [christiandelbianco/monitor-table-change-with-sqltabledependency#110]
Thanks for such a great library. It got me up and running in no time. However I have found that when C# class has Enum the change notifications doesn't work. I am wondering if someone can please double check the issue.  To reproduce the issue you can use the below code.

SQL table script:

```
CREATE TABLE [dbo].[TestResults](
	[TestResultId] [int] IDENTITY(1,1) NOT NULL,
	[JobId] [nvarchar](50) NULL,
	[BuildCode] [nvarchar](50) NULL,
	[CustomerSequenceNumber] [nvarchar](50) NULL,
	[TestStatus]  AS (case when ltrim(rtrim(isnull([ERRORMESSAGE],'')))='' then 'Pass' else 'Fail' end) PERSISTED NOT NULL,
	[ErrorMessage] [nvarchar](512) NULL,
	[TestDate] [datetime] NOT NULL,
	[TotalTimeInSeconds] [decimal](18, 2) NOT NULL,
	[StationId] [int] NOT NULL,
	[ShiftId] [int] NOT NULL,
	[RecipeId] [int] NULL,
	[DuplicateTestResult] [bit] NOT NULL,
 CONSTRAINT [PK_TestResults] PRIMARY KEY CLUSTERED 
(
	[TestResultId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[TestResults] ADD  CONSTRAINT [DF_TestResults_DuplicateTestResult]  DEFAULT ((0)) FOR [DuplicateTestResult]
GO

insert into TestResults
(
JobId
, BuildCode
, CustomerSequenceNumber
, ErrorMessage
, TestDate
, TotalTimeInSeconds
, StationId
, ShiftId
, RecipeId
, DuplicateTestResult
) values 
(
1441820	
, NULL	
, NULL	
, 'Random error'
, '2018-11-26 15:57:50'	
, 120	
, 2	
, 1
, 18	
, 0
)
```

and below C# code:

 ```
public partial class TestResult
{
    public int TestResultId { get; set; }
    public string JobId { get; set; }
    public string BuildCode { get; set; }
    public string CustomerSequenceNumber { get; set; }
    public TestStatus TestStatus { get; set; } //As long as this line is commented everything works
    public string ErrorMessage { get; set; }
    public DateTime TestDate { get; set; }
    public decimal TotalTimeInSeconds { get; set; }
    public int StationId { get; set; }
    public int ShiftId { get; set; }
    public int? RecipeId { get; set; }
    public bool DuplicateTestResult { get; set; }
}

public enum TestStatus
{
    None,
    Pass,
    Fail
}

internal class Program
{
	private static readonly string _connectionString = "Server=someserver;Initial Catalog=somedb;User id=uid;Password=password;MultipleActiveResultSets=True";
	private static void Main(string[] args)
	{
		using (var dep = new SqlTableDependency<TestResult>(_connectionString, "TestResults"))
		{
			dep.OnChanged += Changed;
			dep.OnError += Dep_OnError;
			dep.Start();

			Console.WriteLine("Press a key to exit");
			Console.ReadKey();

			dep.Stop();
		}
	}

	private static void Dep_OnError(object sender, ErrorEventArgs e)
	{
		Console.WriteLine(e.Error);
	}

	public static void Changed(object sender, RecordChangedEventArgs<TestResult> e)
	{
		var changedEntity = e.Entity;
		Console.WriteLine("DML operation: " + e.ChangeType + ", ID: " + changedEntity.TestResultId);
	}
}
```
I have checked the test cases including "EnumTestSqlServer.cs" file. The difference I noticed is that in this file enum is byte type so I am assuming the value stored in DB is number however in my case I am storing string DB (like "Pass"/"Fail") and since I am using EF Core it takes care of converting string to enum.

**Comment by christiandelbianco** [comment]
Thanks for the detailed example used to reproduce the issue.

Fixed: ![capture](https://user-images.githubusercontent.com/13263017/49688221-09112580-fb0f-11e8-8bd8-788be8520e71.JPG)

Upgrade your SqlTableDependency version using the latest NuGet Package.

**Comment by christiandelbianco** [comment]
Test Code used:

`    public enum TestStatus
    {
        None,
        Pass,
        Fail
    }

    public enum TestType
    {
        None = 0,
        UnitTest,
        IntegrationTest
    }

    public class TestResult
    {
        public int TestResultId { get; set; }
        public TestStatus TestStatus { get; set; }
        public TestType TestType { get; set; }
        public string ErrorMessage { get; set; }
    }
`

**Comment by christiandelbianco** [comment]
CREATE TABLE [dbo].[TestResults](
	[TestResultId] [int] IDENTITY(1,1) NOT NULL,
	[TestType] [int] NOT NULL,
	[TestStatus]  AS (case when ltrim(rtrim(isnull([ERRORMESSAGE],'')))='' then 'Pass' else 'Fail' end) PERSISTED NOT NULL,
	[ErrorMessage] [nvarchar](512) NULL,
 CONSTRAINT [PK_TestResults] PRIMARY KEY CLUSTERED 
(
	[TestResultId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

**Comment by christiandelbianco** [comment]
using (var dep = new SqlTableDependency<TestResult>(connectionString, "TestResults"))
            {
                dep.OnChanged += Changed;
                dep.OnError += OnError;
                dep.Start();

                Console.WriteLine();
                Console.WriteLine("Waiting for receiving notifications (db objects naming: " + dep.DataBaseObjectsNamingConvention + ")...");
                Console.WriteLine("Press a key to stop.");
                Console.ReadKey();
            }

        private static void Changed(object sender, RecordChangedEventArgs<TestResult> e)
        {
            Console.WriteLine(Environment.NewLine);

            if (e.ChangeType != ChangeType.None)
            {
                var changedEntity = e.Entity;
                Console.WriteLine("DML operation: " + e.ChangeType + ", ID: " + changedEntity.TestResultId);
                Console.WriteLine("DML operation: " + e.ChangeType + ", TestStatus: " + changedEntity.TestStatus);
                Console.WriteLine("DML operation: " + e.ChangeType + ", TestType: " + changedEntity.TestType);
            }           
        }

**Comment by christiandelbianco** [comment]
Added test case: **EnumTestSqlServer2.cs**

**Comment by nimeshdhruve** [comment]
Can you please confirm I am using the right version as for me I am still not getting notifications. I have used the code you provided for DB as well as C#. Attached image has more details:

![sqlerror](https://user-images.githubusercontent.com/7783989/49689389-909a6c80-faee-11e8-9437-5e63ed9b2968.jpg)

**Comment by christiandelbianco** [comment]
Hi
You must use **8.5.2**.
This version has been just Released.
Regards

**Comment by christiandelbianco** [comment]
Enjoy
