### ISSUE TITLE
After increase the columns string lenght ,Still sqltable dependendency getting limit error.

### ISSUE THREAD

**Issue by testingobject** [christiandelbianco/monitor-table-change-with-sqltabledependency#112]
After changed the columns string length but SQL table dependency generating an error.
"Procedure tr_Board_5fe3b23b-c8d3-4b08-b9a9-e57b5ecae1a1_Sender"
**"String or binary data would be truncated."**

**Comment by christiandelbianco** [comment]
Can you better describe the steps you did to get this error?
