### ISSUE TITLE
SQL Dependency Objects dissapearing

### ISSUE THREAD

**Issue by tverma1** [christiandelbianco/monitor-table-change-with-sqltabledependency#113]
Hi, I have implemented the SQL Dependency in a windows service that monitors a SQL table. It works fine for some time, but after a while, the windows service is still running, but the objects such as triggers, ques and procedures dissappear. This is the error I see in the SQL error log:

BEGIN CONVERSATION TIMER ('02598646-7BF9-E811-822E-819C09A9EC0E') TIMEOUT = 180;WAITFOR (RECEIVE TOP(51) [message_type_name], [message_body] FROM [dbo].[dbo_Table_Name_72badd87-553d-4898-905b-7c573ed1c873_Receiver]), TIMEOUT 120000; 

Is there a setting that I am missing while initializing the dependency?

**Comment by christiandelbianco** [comment]
Hi, as mentioned in the home page:

Windows service using SqlTableDependency must not goes to SLEEP mode or IDLE state. Sleep mode blocks SqlTableDependency code and this result in running the database watch dog that drops all SqlTableDependency's db objects (please see https://stackoverflow.com/questions/6302185/how-to-prevent-windows-from-entering-idle-state).
