### ISSUE TITLE
Support for failover connection

### ISSUE THREAD

**Issue by ComBusJV** [christiandelbianco/monitor-table-change-with-sqltabledependency#114]
Hi Christian,

First of all; awesome project, very easy to use!

Is there a posibility to support failover connectionstrings?

The _manual_ way is to keep the failover connectionstring in 2 connectionstring and monitor their state, but can this be done within the project?

**Comment by christiandelbianco** [comment]
Sorry, no. When the connection is lost, SqlTableDependency cannot reuse same component created previously. At least, not this version.
