### ISSUE TITLE
Non-Generic version

### ISSUE THREAD

**Issue by rlmartins76** [christiandelbianco/monitor-table-change-with-sqltabledependency#119]
Any plans to make available a non-generic version of this library? If not, which workaround would you recommend.

**Comment by christiandelbianco** [comment]
Hi. What is the problem using a generic version? Because there are no plans to  make a non generic version

**Comment by rlmartins76** [comment]
Hi,

The Generic Type only allows a non-interface and non-abstract class as T : class, new().
The issue on my end is that i have a list of tables to monitor (those tables have an ORM c# class, very identical to EF), but the tables that are part of the list arent always the same. I overcome this by using Reflection to create the generic SQLTableDependency<WhateverTableClass>, but i am unable to put persist in memory provider List<T> the instances created for each of my monitored tables, as the common base class is abstract, and other common denominator are interfaces.

Hope this clarifies.

**Comment by christiandelbianco** [comment]
Qatar

**Comment by christiandelbianco** [comment]
Understood. But i there is no plan to make it not generic. Sorry
