### ISSUE TITLE
Get notification of value that is not mapped

### ISSUE THREAD

**Issue by mniess** [christiandelbianco/monitor-table-change-with-sqltabledependency#121]
Is it possible to get notified about a change in a value, that is not mapped?

In my specific excample is a "is_deleted" column, that is not used in the object, as it is simply deleted/created on change.

**Comment by christiandelbianco** [comment]
Yes, it is possible.

**Comment by christiandelbianco** [comment]
https://github.com/christiandelbianco/monitor-table-change-with-sqltabledependency/wiki/Use-case:-Specify-for-which-properties-we-want-receive-notification-using-UpdateOfModel-T--mapper

**Comment by mniess** [comment]
Oh yeah! Sorry I read only about the mapper.

Thanks for this tool, wiki and support. 
Keep up the good work!

**Comment by mniess** [comment]
Could you please give an example how this works? 
In your example I want to track changes of the `Born` DB column without adding it to the `Person` model.

**Comment by christiandelbianco** [comment]
Understood. N earlier
