### ISSUE TITLE
error on SqlTableDependency.Start()

### ISSUE THREAD

**Issue by rjaiswar** [christiandelbianco/monitor-table-change-with-sqltabledependency#122]
Hello Team,
I am getting below error on SqlTableDependency.Start().

**System.Data.SqlClient.SqlException: 'A transport-level error has occurred when receiving results from the server. (provider: TCP Provider, error: 0 - The semaphore timeout period has expired.)'**

My sql login user is dbo_owner. and database connection also working but when SqlTableDependency.Start() that get error.

**Comment by rjaiswar** [comment]
No it's not on azure cloud.

**Comment by rjaiswar** [comment]
When i am co

**Comment by pseabury** [comment]
> Is your db hosten in Azure cloud?

Does SqlTableDependency support SqlAzure?  I suppose NO because of the broker dependency?

Paul

**Comment by christiandelbianco** [comment]
No, SqlTableDependency does NOT support SqlAzure

**Comment by christiandelbianco** [comment]
Is there a way form me to reproduce this error?
