### ISSUE TITLE
High CPU Usage

### ISSUE THREAD

**Issue by Swellenator** [christiandelbianco/monitor-table-change-with-sqltabledependency#123]
Hi 

I have set up SqlTableDependency on a single small table inside an ASP.NET website. Very basic setup. It's works fine, but my CPU usage seems to be stuck at 20% for SQL Server. When I kill the website process it goes back to 0%.

If I look at expensive queries I see 

`BEGIN CONVERSATION TIMER ('8C887D4D-EF28-E911-8EC5-F44D300638ED') TIMEOUT = 180;WAITFOR (RECEIVE TOP(8) [message_type_name], [message_body] FROM [MySchema].[MySchema_MyTable_c6ef7b2d-ccf0-44ba-beb6-38a457b32b7b_Receiver]), TIMEOUT 120000;`

The query stats has `total_elapsed_time` as 3240045837. 

Any ideas what this is, and is it working correctly. I think it is doing something wrong to be using so many resources.

Thanks

**Comment by christiandelbianco** [comment]
Hi. The SQL query you pointed out, it is executed by SqlTableDependency and it is a standard query used to monitor sql server messages in a queue. So, there is nothing wrong.
