### ISSUE TITLE
Event does not fire on a restored database

### ISSUE THREAD

**Issue by crong-tek** [christiandelbianco/monitor-table-change-with-sqltabledependency#126]
I created a new database and SqlTableDependency worked perfectly. I then restored a production database into my test environment, the code stopped working. The event just does not fire anymore.

I noticed below description in the readme. Does that mean this code does not work with the restored database?
"Database Backup and Restore: restoring SqlTableDependency's db objects, it does not work."

Thanks
Chris

**Comment by christiandelbianco** [comment]
When the SQL Server connection is close, SqlTableDepenndency is not any more connected to DB objects its created and there is not anymore possibility to re-estabilish this connection.

**Comment by crong-tek** [comment]
Hi, Christian, after the database is restored, I ran the program again to try to catch the db changes. I can see the trigger was created by SqlTableDependency again but for some reason SqlTableDependency does not fire any change event. I restarted SQL server and software a few times, but nothing changed.

My database is not big so I created script and then ran the script to re-generate the database and data. Surprisingly the software worked again. 

Thus I am not sure what is the difference between the restored database and the one generated by script. Maybe I missed something. The only thing special is the database contain file stream. If you know anything related, please let me know. I will test another normal database today.

**Comment by christiandelbianco** [comment]
As told before, once SqlTableDependency loose connection to DB, there is not way to re-attach its self to trigger/queue and sql server broker.

**Comment by christiandelbianco** [comment]
Also, SqlTableDependency DB's objects are still in DB because making the backup and restore, the watchdog that take care of removing that object is not anymore active.
