### ISSUE TITLE
Question about compatibility

### ISSUE THREAD

**Issue by luky92** [christiandelbianco/monitor-table-change-with-sqltabledependency#127]
Is it enough to set compatibility level of SQL 2005 created database to SQL server 2008 r2 for sqltabledependancy to work as intended? I tested it and it seems so just making sure

**Comment by christiandelbianco** [comment]
Hi, I do not get the point. Can you explain me better?

**Comment by luky92** [comment]
I have a database that has a dbi_createversion value of SQL 2000 however when I connect to it using the library I receive notifications normally and I'm trying to understand why

**Comment by christiandelbianco** [comment]
WONDERFUL! If you find the reason, can you let me know.
I will put you as contributor!

**Comment by luky92** [comment]
I will be sure to let you know :)

**Comment by luky92** [comment]
Question did you have any significant changes to the code form version 6 to 7 because i tested the database with all the versions avalible on nuget and all work like charm?

**Comment by christiandelbianco** [comment]
Of course there are. Starting from version 8, a huge error was fixed.
I seriously suggest you to use last version.

**Comment by luky92** [comment]
Did you ever know what was the technical reason that caused  the older databases not to work? Asking this because currently my theory is that it there was something causing the incompatibility and then it was removed/changed so that the only requirement is to host the database using SQL Server 2008 r2

**Comment by christiandelbianco** [comment]
Did you ever know what was the technical reason that caused the older databases not to work? --> NO, i do not know.
