### ISSUE TITLE
'StatusChangedEventArgs' issue on local environment

### ISSUE THREAD

**Issue by umarsolehri** [christiandelbianco/monitor-table-change-with-sqltabledependency#128]
error CS1061: 'StatusChangedEventArgs' does not contain a definition for 'CultureInfo' and no accessible extension method 'CultureInfo' accepting a first argument of type 'StatusChangedEventArgs' could be found (are you missing a using directive or an assembly reference?)

![issue-](https://user-images.githubusercontent.com/15965524/53470756-62408380-3a84-11e9-8530-dc88a3cda032.png)

the error coming on windows and running fine on IIS server

if any change occurs state remain still **'WaitingForNotification'**

**Comment by christiandelbianco** [comment]
Hi,
can you provide the needed steps to reproduce this problem?
Otherwise i cannot investigate.

**Comment by umarsolehri** [comment]
you mean code ?

**Comment by umarsolehri** [comment]
public class CommentHubService
    {
        private string ConnectionString { get { return System.Configuration.ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString; } }
        private readonly static Lazy<dynamic> _instance = new Lazy<dynamic>(() =>
        new CommentHubService(GlobalHost.ConnectionManager.GetHubContext<CommentHub>().Clients));

        private static SqlTableDependency<CommentModel> _tableDependency;
        public static CommentHubService Instance { get { try { return _instance.Value; } catch { return null; } } }
        private IHubConnectionContext<dynamic> Clients { get; set; }

        public CommentHubService(IHubConnectionContext<dynamic> clients)
        {
            Clients = clients;

            var mapper = new ModelToTableMapper<CommentModel>();
            mapper.AddMapping(e => e.CommentId, "CommentId");
            //mapper.AddMapping(e => e.Comment, "Comment");
            //mapper.AddMapping(e => e.CommentDate, "CommentDate");
            //mapper.AddMapping(e => e.OrderId, "OrderId");
            //mapper.AddMapping(e => e.UserId, "UserId");
            //mapper.AddMapping(e => e.RoleId, "RoleId");

            _tableDependency = new SqlTableDependency<CommentModel>(ConnectionString, "Comments", mapper, null, null, DmlTriggerType.All);

            _tableDependency.OnChanged += _tableDependency_OnChanged;
            _tableDependency.OnStatusChanged += _tableDependency_OnStatusChanged;
            _tableDependency.OnError += _tableDependency_OnError;

            //_tableDependency.TraceLevel = TraceLevel.Verbose;
            //_tableDependency.TraceListener = new TextWriterTraceListener(Console.Out);

            _tableDependency.Start();
        }

        private void _tableDependency_OnError(object sender, ErrorEventArgs e)
        {

        }

        private void _tableDependency_OnStatusChanged(object sender, StatusChangedEventArgs e)
        {

        }

        private void _tableDependency_OnChanged(object sender, RecordChangedEventArgs<CommentModel> e)
        {
            if (e.ChangeType == ChangeType.Insert)
            {
                //Clients.Group("contentComment_" + e.Entity.KeywordMetaId).PushNewComment(e.Entity);
            }
        }

        //private void _tableDependency_OnChanged(object sender, RecordChangedEventArgs<CommentModel> e)
        //{
        //    if (e.ChangeType == ChangeType.Insert)
        //    {
        //        //Clients.Group("contentComment_" + e.Entity.KeywordMetaId).PushNewComment(e.Entity);
        //    }
        //}

        private void SqlTableDependency_Changed(object sender, RecordChangedEventArgs<CommentModel> e)
        {
        }


        #region IDisposable Support
        private bool disposedValue = false; // to detect redundant calls

        protected virtual void Dispose(bool disposing)
        {
            if (!disposedValue)
            {
                if (disposing)
                {
                    _tableDependency.Stop();
                }
                disposedValue = true;
            }
        }
        ~CommentHubService()
        {
            Dispose(false);
        }
        // This code added to correctly implement the disposable pattern.
        public void Dispose()
        {
            Dispose(true);
            GC.SuppressFinalize(this);
        }
        #endregion
    }

**Comment by umarsolehri** [comment]
![image](https://user-images.githubusercontent.com/15965524/53475068-cc5f2580-3a90-11e9-8173-fe8679939e55.png)

**Comment by umarsolehri** [comment]
i don't know why trigger is not running, I only got this difference while running on windows and IIS

**Comment by christiandelbianco** [comment]
The code example using SignalR is very only and I am not sure that is 100% compatible with latest version of SqlTableDependency.Can you check which version of SqlTableDependency are you using?

**Comment by umarsolehri** [comment]
8.5.3

**Comment by umarsolehri** [comment]
It running perfectly on Windows Server 2012 but causing issue on windows,
I connected my project which is running on windows and connected to Database which is on Server it triggers the notification but when I connect to db on local nothing happens.

**Comment by umarsolehri** [comment]
which service is required for running this, if any i will check may be some services are stopped so they causing a issue

**Comment by christiandelbianco** [comment]
So, as resume:
- if you use a Sql Server database hosted on Windows Server 2012, all work fine.
- if you use a Sql Server database hosted on your local Windows, it does not works.

Question: when you run your application using Sql Server database hosted on your local Windows, can you see a new the trigger created on your database table?

**Comment by umarsolehri** [comment]
trigger and stored procedure both were created

**Comment by umarsolehri** [comment]
![image](https://user-images.githubusercontent.com/15965524/53622141-ab2a4080-3c1a-11e9-8165-87fa2481670d.png)
![image](https://user-images.githubusercontent.com/15965524/53622159-bda47a00-3c1a-11e9-9122-996bc7d71e0d.png)

**Comment by christiandelbianco** [comment]
and the query you have run on DB to check its compatibility level is on Sql Server database hosted on your local Windows?

**Comment by umarsolehri** [comment]
already mentioned in previous comment

**Comment by christiandelbianco** [comment]
Can you backup your local DB (removing all unnecessary tables and data), tip and send to me?

**Comment by umarsolehri** [comment]
[script.zip](https://github.com/christiandelbianco/monitor-table-change-with-sqltabledependency/files/2919102/script.zip)

**Comment by christiandelbianco** [comment]
no, i need the BACKUP of your DB. Otherwise i cannot have the same environment you have.
Of course, remove all sensitive data before make the backup. Just leave the table you need to monitor.

**Comment by ofcerci4826** [comment]
I have same problem, Can you find a fix ?
