### ISSUE TITLE
Incorrect syntax near 'POISON_MESSAGE_HANDLING'.

### ISSUE THREAD

**Issue by aristid-lavri** [christiandelbianco/monitor-table-change-with-sqltabledependency#13]
Hi 
I get the error bellow when the SqlTableDependency start method is launched

**An exception of type 'System.Data.SqlClient.SqlException' occurred in System.Data.dll but was not handled in the user code

Additional Information: Incorrect syntax near 'POISON_MESSAGE_HANDLING'.**

can you help me ?

**Comment by christiandelbianco** [comment]
Which SQL Server version are you using ?

**Comment by aristid-lavri** [comment]
2008

**Comment by christiandelbianco** [comment]
2008 R2 ?

**Comment by christiandelbianco** [comment]
Home page clearly specify that:

.NET 4.6.1
SQL Server >= 2012

**Comment by Mhd1992** [comment]
how can i fix this error 'Incorrect syntax near 'POISON_MESSAGE_HANDLING
i am using sqlserverexpress 2014 and framework 4.5.2

**Comment by jaystead** [comment]
@Mhd1992 Hey I noticed you were recently having the same issue I have I was wondering if you made any progress on Poison message handling? I saw where turning it off with: 
ALTER QUEUE {queryName}
WITH POISON_MESSAGE_HANDLING (STATUS = OFF)
GO

seemed to work for some people but it could cause bigger issues down the line
