### ISSUE TITLE
Sql Dependency stop after error event. I need to reconnect it withour iis reset

### ISSUE THREAD

**Issue by testingobject** [christiandelbianco/monitor-table-change-with-sqltabledependency#132]
On error event i have write email function to get aware of sql dependency is stop. in that case i have to reset iis. so sql dependency start again. But i need some suitable solution.  As in day 10-15 times this stop.

I have google lot but nothing find suitable. I think need some stuff here in hub

	public override Task OnConnectedAsync()
        {
	      return base.OnConnectedAsync();
        }

	public override Task OnDisconnectedAsync(Exception exception)
	{
	     return base.OnDisconnectedAsync(exception);
	}

**Comment by christiandelbianco** [comment]
You cannot reconnect. Once connection is lost, you cannot reconnect SqlTableDependency to already existing object in DB. and by the way, those db object should be removed authomaticly after 3 minutes.

**Comment by testingobject** [comment]
Then what is solution. As i am getting this error most time in day. So IIS reset is only last solution?

**Comment by christiandelbianco** [comment]
As i wrote, when an error happen there is not way to re-use previously SqlTableDependency database's objects. You must create a new SqlTableDependency 's instance to get notifications.

**Comment by christiandelbianco** [comment]
if you really need to "reconnect it withour iis reset", you must implement a custom solution.
In the earlier versions, that was possible, but that i had to remove.

**Comment by testingobject** [comment]
IIS reset is not good solution. Can i use OnDisconnected event to again create new instance?
I have use this but not working properly.

**Comment by christiandelbianco** [comment]
Hi. Detail on how YOUR application works are known only by you. The only think that i can tell you is that there is no way to re-establish a second connection to already existing SqlTableDependency database objects.

**Comment by testingobject** [comment]
I have 7 tables in db. I am using their OnChanged,OnError,OnstatusChanged events.
On Error event i have write Email code that tell me Real updates stop working. 

structure as follows:                                                                                                                                                  
private  SqlTableDependency<DataModelLayer.Models.Board> _tblA;
public void Configure(string connectionString)
{
Creating table A new instance and their dynamic events.
}

So i am using Configure Event again inside
private void _tableDependency_OnError(object sender, ErrorEventArgs e)
Is there anything wrong?

**Comment by testingobject** [comment]
I am calling one error event for all 7 tables. so if error occurs then i am forcefully calling Configure  method for creating new instance of each table and their dynamic events.

**Comment by testingobject** [comment]
Now on OnStatusChnaged Event I am checking if dependency stop due to error then i am creating new instance for dependencyf for that particular table only. Till now this is working fine. I am testing it.

**Comment by testingobject** [comment]
Hi Admin I have some questions about Sql dependency
1. When this run then some triggers and procedure created in db. How long they remain in db?
2. In my case sql dependency stop after some time. So on error i have got table name and then do following:
1. Stop that table dependency
2. Create new one for that table.
But I have notices there are many triggers and procedures created in db. Please correct me.

**Comment by christiandelbianco** [comment]
1. when SqlTableDepdendency runs ONLY ONE trigger and is generated on the table that is monitored.
2. when Stop() is invoked all databases objects created by SqlTableDependency are dropped
3. Is the sql connection is closed for any reason - for example you are debugging and stop the debug without invoking Stop(), after 3 minutes all all databases objects created by SqlTableDependency are dropped.

**Comment by christiandelbianco** [comment]
@testingobject : for ANY doubt, please check all integration tests in the solution. I always check that DB objects are disposed
