### ISSUE TITLE
Problem with Stop and Start

### ISSUE THREAD

**Issue by Talpidae1** [christiandelbianco/monitor-table-change-with-sqltabledependency#134]
I'm using sqltabledependency and added a functionality to restart everything, if a problem occured (DB was unavailable etc).
To archive this, I'm calling SqlTableDependency.Stop() and .Start(). 
However, everytime I do this SQLTableDependency seems to react multipe times. For example, if I restart it 3 times, I will got 4 reactions to table changes afterwards.
Am I doing anything wrong, or is there a bug?
When I check the database, there are just 1-2 Contracts, Queues and Services, even if I get 4 reactions to table changes.

**Comment by testingobject** [comment]
Hi i have also the same issue. In my case sqltabledependency stop after some time. so on Statuschange inside try catch getting table name. Then i have create new method where i have pass table name so on this basis i am restarting only that table instance. But i am confused about their working.

**Comment by christiandelbianco** [comment]
@Talpidae1 Hi, can you describe how to reproduce this issue. I created ad integration test (**StopAndStartTest** you can see in GIT repository), but it works with no problem.
Would you explain me what you did to get the error?

**Comment by Talpidae1** [comment]
Thank you for adding the tests. I just noticed the error was on our side (multiple subscriptions), so this issue can be closed. Sorry for wasting your time and thank you for this great framework.

**Comment by christiandelbianco** [comment]
Ok, then i will close thit ticket.
