### ISSUE TITLE
How can I demonise SqlTableDependency listener?

### ISSUE THREAD

**Issue by sayuj** [christiandelbianco/monitor-table-change-with-sqltabledependency#135]
```
       public void Notify()
        {
            using (var dep = ModelDependency())
            {
                dep.OnChanged += Changed;
                dep.Start();
                Console.ReadKey();
            }
        }
```

This is getting closed when I press a key. I want my listener listen until I stop it forcefully. It is getting killed because `WaitForNotifications` is defined as `async`. Is there any other method to use it as `sync`?

**Comment by christiandelbianco** [comment]
Have a look to https://github.com/christiandelbianco/monitor-table-change-with-mvc-signalR-jquery-sqltabledependency-example
In this example SqlTableDependency is hosted in a Web Application

**Comment by sayuj** [comment]
@christiandelbianco I don't have any web application. It is a stand alone back end worker/daemon.
