### ISSUE TITLE
equivalent to trigger_nestlevel

### ISSUE THREAD

**Issue by tobiasfeil** [christiandelbianco/monitor-table-change-with-sqltabledependency#136]
I would like having a functionality that prevents the tabledependency from triggering itself when it changes the table it is attached to, like trigger_nestlevel in an sql trigger. Does this exist? Thank you!

**Comment by christiandelbianco** [comment]
Hi, I do not understand what you want. Can you try to explain me again, making an example?
Thanks

**Comment by christiandelbianco** [comment]
I close it because this is not an ISSUE but a question

**Comment by tobiasfeil** [comment]
For sure. Picture the following scenario: Whenever data is changed in table A, I want to check some conditions and possibly update other rows in the same table, table A.

If I do this with SQLTableDependency, an infinite loop is created like this:

table A is changed -> SQLTableDependency is triggered and changes table A -> SQLTableDependency is triggered and changes table A ->SQLTableDependency is triggered and changes table A...

Is it clear what I mean?

I'm looking for a way to prevent creating an infinite loop.

**Comment by christiandelbianco** [comment]
Now it is clear.
No, there is no way to do that.

**Comment by tobiasfeil** [comment]
Very well, thank you for clarifying.
