### ISSUE TITLE
SqlTableDependency user with no permissions

### ISSUE THREAD

**Issue by Khilborn** [christiandelbianco/monitor-table-change-with-sqltabledependency#137]
Is there any way to get around the user check.  We have tons of application that connect to our databases just fine within our domain yet using TableDependecy, we get this problem

**Comment by christiandelbianco** [comment]
"Is there any way to get around the user check." ?
YES. Set the **executeUserPermissionCheck** constructor parameter to FALSE. But remember that if the user has not sufficient grants, you will get an exception during the SQL objects creations (trigger, queue etc).

**Comment by Khilborn** [comment]
There is no such parameter on the constructor.

**Comment by Khilborn** [comment]
Runtime version v4.0.30319

**Comment by christiandelbianco** [comment]
PLEASE update to latest version 8.5.3

**Comment by Khilborn** [comment]
I am getting it through NuGet through Visual Studio.

**Comment by christiandelbianco** [comment]
Use latest version 8.5.3, because the 4.8.2.0 is a **prehistoric** version with bugs.

**Comment by Khilborn** [comment]
I was referencing the dll's themselves. I doubled checked and v8.5.3 is installed via NUGet yet that parameter is not there.

**Comment by Khilborn** [comment]
I have resolved the issue. Thanks
