### ISSUE TITLE
Most performant way to temporarily disable an existing dependency

### ISSUE THREAD

**Issue by tobiasfeil** [christiandelbianco/monitor-table-change-with-sqltabledependency#140]
Hello,

I am writing a syncing application that syncs between two tables, both tables have an sqltabledependency attached to them. When a change in one table is detected, it is supposed to sync the data to the other table without triggering the dependency there. 

What is the best way to temporarily disable the sqltabledependency in the other table? I've seen that calling `dep.Stop` and `dep.Start()` takes some time. Therefore, my approach right now is to just temporarily disable all sqltabledependency triggers on the other table.

Is this the right approach or is there a better one?

Thank you!

P.S. I'm sorry I don't know how to label this as a question, or else I would do it since this is not a feature proposal.

**Comment by christiandelbianco** [comment]
Hi. There is no way to temporarly disable sqltabledependency notifications. Also, stopping and restarting sqltabledependency is not a good solution, as it create a new set of db objects (queue, service broker, trigger)

**Comment by tobiasfeil** [comment]
I think this would be an awesome feature for a future version :)
