### ISSUE TITLE
Use it with SQL Server 2017 (RTM)

### ISSUE THREAD

**Issue by cesarriva** [christiandelbianco/monitor-table-change-with-sqltabledependency#142]
Hi, is it possible to use with the version SQL Server 2017 (RTM)?

I just tried to run the main example, everything runs fine (no exceptions and the console app starts ok), however, when I update or add something in my database using the SQL Management Studio, I don't receive the notification in the event callback.

**Comment by christiandelbianco** [comment]
One question: your DATABASE file was created using which Sql Server version?
Can you try to test using a DB created using SQL Server 2017?

**Comment by cesarriva** [comment]
Hi, thanks for the reply.

So, I created the db using the SQL Management Studio.
I'm using my SQLEXPRESS instance for the test.

I run the compatibility script you propose and the result is like this:
Field                          VALUE      SQLVersion
dbi_version	          869	  ?
dbi_createVersion	  869	  ?

It's weird, because all the SQL objects are created when I run the application. I mean, the trigger, the store proc, and also all the Service Broker objects messages, queues, etc).

**Comment by christiandelbianco** [comment]
I can confirm you that using **SQL Server 2017** i have the same problem.

**Comment by christiandelbianco** [comment]
Started bug fix.

**Comment by cesarriva** [comment]
Hi Christian, 

I managed here. It was something related to my db schema and permissions.
When I changed the owner of the database to sa, the event started to be triggered.

I run this: ALTER AUTHORIZATION ON DATABASE::myDbNameHere TO sa;

Don't understand why but now it's working.

Thanks

**Comment by christiandelbianco** [comment]
Yes, indeed. I just check again, using SQL Server 2017 and it **works**.
I will close the bug.
