### ISSUE TITLE
Sql Objects naming: is static GUID possible?

### ISSUE THREAD

**Issue by logicalrshabani** [christiandelbianco/monitor-table-change-with-sqltabledependency#143]
As i saw each time we call Start() sql objects like trigger, procedures, queues etc are generated containing inside the name a GUID. So wen we call Stop(), using this GUID we can delete these objects from the database.
Suppose for some reason the app is forcibly closed, some system crash occures or energy failure causes shutdown. These object remains there and the next time we call Start/Stop new object withe new generated GUID are created/destroyd.
Is there any way to make such GUID persistent so that the application context can persist also when system failure occures?

**Comment by christiandelbianco** [comment]
Hi, at the moment there is not way to re-use SQL objects (like trigger, procedures, queues etc) previously created.
