### ISSUE TITLE
Timout exception

### ISSUE THREAD

**Issue by ThomasPaganelli** [christiandelbianco/monitor-table-change-with-sqltabledependency#144]
Hi 

I have an issue when I create  my SqlTableDependency, I'm having a connection timeout exception when the app start.

It was working before, nothing changed, I just restart my local IIS Server.

Object is created inside my Application_Start() : 

    protected void Application_Start()
    {
            AreaRegistration.RegisterAllAreas();
            RouteConfig.RegisterRoutes(RouteTable.Routes);

            var conStr = ConfigurationManager.ConnectionStrings[0].ConnectionString;

            var mapper = new ModelToTableMapper<Job>();
            mapper.AddMapping(model => model.Seq, "seq");
            mapper.AddMapping(model => model.User, "user");
            mapper.AddMapping(model => model.Whn, "whn");
            mapper.AddMapping(model => model.ReasonCode, "reasonCode");
            mapper.AddMapping(model => model.Src, "src");

            _dependency = new SqlTableDependency<Job>(conStr, "JobQueue", mapper: mapper);
            _dependency.OnChanged += _dependency_OnChanged;
            _dependency.OnError += _dependency_OnError;
            _dependency.OnStatusChanged += _dependency_OnStatusChanged;

            _dependency.Start();
    }

Any idea ?

**Comment by ThomasPaganelli** [comment]
OK I may have found the issue...

The query instantiated by CheckIfUserHasPermissions() is taking a lot of time on my SQLServer and return no row :/

I setted executeUserPermissionCheck to false in the constructor and it's running well now.

The only thing I don't get is why it was working fine before with executeUserPermissionCheck to true ^^'

Cheers

**Comment by christiandelbianco** [comment]
Good.
Is all is solved, can you close this BUG?
Thanks
