### ISSUE TITLE
How to cleanup the SQL table dependency conversations

### ISSUE THREAD

**Issue by swapnashinde** [christiandelbianco/monitor-table-change-with-sqltabledependency#145]
Hi, I am using SQL table dependency in a windows service. This creates thousands of conversations in the database. How to end all the conversations ?

**Comment by christiandelbianco** [comment]
Lost Conversation handlers are removed from the following code present in stored procedure with naming XXXX_QueueActivationSender

 SELECT conversation_handle INTO #Conversations FROM sys.conversation_endpoints WITH (NOLOCK) WHERE far_service LIKE N'dbo_CancellationTokenTestModel_6ffab187-b7de-4ea2-be41-6fff5b6b8cb4_%' ORDER BY is_initiator ASC;
        DECLARE conversation_cursor CURSOR FAST_FORWARD FOR SELECT conversation_handle FROM #Conversations;
        OPEN conversation_cursor;
        FETCH NEXT FROM conversation_cursor INTO @conversation_handle;
        WHILE @@FETCH_STATUS = 0 
        BEGIN
            END CONVERSATION @conversation_handle WITH CLEANUP;
            FETCH NEXT FROM conversation_cursor INTO @conversation_handle;
        END
        CLOSE conversation_cursor;
        DEALLOCATE conversation_cursor;
        DROP TABLE #Conversations;
