### ISSUE TITLE
Key column mapping does not work

### ISSUE THREAD

**Issue by tomasfabian** [christiandelbianco/monitor-table-change-with-sqltabledependency#146]
Hi, we have a database table with key column int IdBank and we are mapping it to Id in our poco class. The Id is always 0 during insert, update or delete. Example:
      var mapper = new ModelToTableMapper<Bank>();
      mapper.AddMapping(c => c.Id, "IdBank"); // dbo,Bank.IdBank (PK, int, not null)

      using (var sqlTableDependency = new SqlTableDependency<Bank>(connection, "Bank", mapper: mapper))
      {
        sqlTableDependency.OnChanged += Changed;
        sqlTableDependency.Start();
      }

    public static void Changed(object sender, RecordChangedEventArgs<Bank> e)
    {
      var changedEntity = e.Entity;

      Console.WriteLine("ID: " + changedEntity.Id);
    }
  public class DomainObject
  {
    public int Id { get; set; }
  }

  public partial class Bank : DomainObject
  {
  }

Thank you Tomas

**Comment by christiandelbianco** [comment]
Hi Tomas,
I changed and i can tell you that you found a BUG.
**Working on its FIX.**

Regards

**Comment by christiandelbianco** [comment]
Fixed. Please check test **TableDependency.SqlClient.Test\Issue146Test.cs** present on this repository.
Fix released with version 8.5.4

**Comment by tomasfabian** [comment]
Thx for the fix
