### ISSUE TITLE
Pass Table instead of Class object

### ISSUE THREAD

**Issue by IzzyGo** [christiandelbianco/monitor-table-change-with-sqltabledependency#147]
Dear Christian,

I would very much like to be able to just pass an empty table  with matching schema to a new instance of SQLTableDependency instead of first having to create a class object for the table. And then receive back all changed rows with their rowstates when the respective event fires.

Would this be possible? It is quite cumbersome to have to set up classes for all relevant tables and keep these classes up-to-date with possible changes made to table columns. 

Thanks!

**Comment by christiandelbianco** [comment]
Hi IzzyGo,
I am sorry, but what you are asking me is currently impossible.
Regards

**Comment by IzzyGo** [comment]
hello christian. that is sad. is there a flaw in my logic? am i missing something? i very much like your approach of havins sql push changes instead of pulling them in an interval. however, i need the changes in a table that can be MERGEd with an existing table to update the existing table (special case are deletions). would that be hard to implement? i would even pay something for it. thank you for your time, and of course, i would accept your second no to my request. best regards, marc

**Comment by christiandelbianco** [comment]
"_I would very much like to be able to just pass an empty table with matching schema to a new instance of SQLTableDependency instead of first having to create a class object for the table. And then receive back all changed rows with their rowstates when the respective event fires._" 

This result can be achieved only if i return back a Dictionary<string, object> where string is the column name and object id the new table column value.

However, this requires a huge change and it will be a custom (that is only for you) implementation.

**Comment by IzzyGo** [comment]
Hello Christian,

 

I see that this would cause major work and also that it appears to only be useful for me, so it does not make sense that you spend time on it. I am nevertheless thankful for your reply. I will try to work out another way to reduce traffic, possible working with a record timestamp, should be easy.

 

I like your approach though, cool concept.

 

Thanks for your time and all the best!

Marc

 

 

Von: Christian Del Bianco <notifications@github.com> 
Gesendet: Montag, 17. Juni 2019 20:24
An: christiandelbianco/monitor-table-change-with-sqltabledependency <monitor-table-change-with-sqltabledependency@noreply.github.com>
Cc: IzzyGo <men74@me.com>; Author <author@noreply.github.com>
Betreff: Re: [christiandelbianco/monitor-table-change-with-sqltabledependency] Pass Table instead of Class object (#147)

 

"I would very much like to be able to just pass an empty table with matching schema to a new instance of SQLTableDependency instead of first having to create a class object for the table. And then receive back all changed rows with their rowstates when the respective event fires."

This result can be achieved only if i return back a Dictionary<string, object> where string is the column name and object id the new table column value.

However, this requires a huge change and it will be a custom (that is only for you) implementation.
