### ISSUE TITLE
How to best retrieve messages that could not be received by .Net Client in case of its inactivity?

### ISSUE THREAD

**Issue by skashif** [christiandelbianco/monitor-table-change-with-sqltabledependency#148]
**Thanks for your work on this library**.

I am trying to find answer to the following question -
Let's say I am using SQL dependency on a table via a data observer service which is nothing but a simple windows service (.Net client). When the service starts it establishes the dependency connection (.Start()) and we start receiving the notification for any changes to the table we are observing. 
But, let's say your observer service is down during production hours which means connection is disposed and we loose the change notification period during the down time. 

_Cheating logic is to not kill the generated trigger that puts the xml messages in the queue and the service that feeds of that queue, but the problem is when the observer service comes back up it will establish a new connection (.Start()) which will create new trigger/sproc/queue/service and we loose previous queue and our offline stored change notifications are killed as well. Is there any way we could reuse the queue/service/trigger when we establish a connection?_

I would highly appreciate if any one could share a sophisticated way to replay these change messages when the service comes back up. Please feel free to expand the suggestion scope outside the library in use.

_P.S. The main reason for this concern is that the update messages received by the observer is going to be sent to another receiver that uses it for calculation and persist data in its DB, not taking care of lost messages due to inactivity means the values are not in sync (it is okay during the period of inactivity) when we are back up and also we loose audit_

**Comment by christiandelbianco** [comment]
Hi. Time ago, there was the possibility to not **destroy** the trigger. So, even if the connection was close, the trigger collected record changes in the queue. Then, when SqlTableDependency was started again, it gets these changed from the queue and start notify clients. Now is not present anymore. Why? Because people having two SqlTableDependency instances wanted to get notification for both SqlTableDependency instances...but this cannot work!

**Comment by skashif** [comment]
Hi Chris, thank your for replying.

I agree with your point of not providing notification for more than 1 SqlTableDependency instances, as it leaves too many open cases to handle.

Is there something you would recommend in my specific example? Any suggestion is more than welcome as I am trying to wrap my head around the failure scenarios and what would be the false safe options.

**Comment by christiandelbianco** [comment]
In any case, release 9.x will have the possibility to "reconnect" SqlTableDependency to its database object, retrieveing data changed that have been done while the connection was closed.

**Comment by dongfo** [comment]
I am testing a modified lib , in which, user card deteermind when to destrory database object.
so when the app crashed ,you can restart again to receive message from queue, no hurry for lost message. if you want to destroy database object you need to call the destory method yourself.
and no more need to get conversation handler id. the trigger just reuse the actived one or create a new.
