### ISSUE TITLE
Allow user to pass in Guid to create the trigger with?

### ISSUE THREAD

**Issue by GSUFan513** [christiandelbianco/monitor-table-change-with-sqltabledependency#149]
ENHANCEMENT REQUEST - see commit below for my suggestion

https://github.com/GSUFan513/monitor-table-change-with-sqltabledependency/commit/24bfa3ea058dad5794e639599faadac2faba3d24

Currently, we need a way to poll our database and check for a trigger on that table, however if there are multiple triggers on the table, we cannot be positive that one of the ones on there is the one we are looking for.

This commit allows me to pass in the triggers guid to create. This way when we poll sql for the triggers on the table, we are positive the one we started with is still there and functioning. This should have no effect on any users.

Alternatively, you could provide the Guid you are using in a public property if that's easier, but I would REALLY appreciate seeing this code in there as soon as possible.

**Comment by christiandelbianco** [comment]
Hi, with GetBaseObjectsNamingConvention() you can have the naming convention used to create all DB objects. Is not enough?

**Comment by GSUFan513** [comment]
Ah, I missed this method. I think that is fine for our usage.

Thanks.
