### ISSUE TITLE
Subscribe to an existing subscription

### ISSUE THREAD

**Issue by s0v4** [christiandelbianco/monitor-table-change-with-sqltabledependency#15]
Hi Christian,

I just wondered what the rationale was when deciding to force tearing the subscription setup down (i.e. the SqlTableDependency infrastructure such as Trigger, Service Broker service, the queue, etc.), whenever application stops (either gracefully or crashing).

Would it be at all possible to leave infrastructure intact thus subscribe back to it on next startup?
That way subscriber would not miss out any messages. 

Many thanks

**Comment by christiandelbianco** [comment]
Hi. This is not a bug. It is the behavior of this component.
To response you: there was this possibility, in previous release. It has been removed, because it was almost impossible execute the clean-up in case user decide to remove DB objects.

**Comment by miguelcudaihl** [comment]
Hi @christiandelbianco I think that durable subscription is a rather common use case.  What can be done is create a table which will log all your object creation metadata and let objects survive subscriber restarts.  If the user needs to teardown the subscription objects, then refer to the metadata table.

I'll see if I can find time to help out implementing this.
