### ISSUE TITLE
not work

### ISSUE THREAD

**Issue by TarrahArshad** [christiandelbianco/monitor-table-change-with-sqltabledependency#152]
i installed code but change in table not affect handle code
only i see in db added trigger but change not fire in code

**Comment by christiandelbianco** [comment]
Can you show me how do you uses SqlTableDependency?

**Comment by christiandelbianco** [comment]
closed because no feedback.

**Comment by TarrahArshad** [comment]
hi

**Comment by TarrahArshad** [comment]
i see today you email i send you tommorow code

**Comment by TarrahArshad** [comment]
class Program
    {

        static void Main(string[] args)
        {
            // start synce
            //  await PeriodicFooAsync(new TimeSpan(0, 0, 10), CancellationToken.None);
            using (var dep = new SqlTableDependency<Product>("data source=.;initial catalog=itdcloud;Integrated Security=true;", "Products"))
            {
                dep.OnChanged += Changed;
                dep.Start();

                Console.WriteLine("Press a key to exit");
                Console.ReadKey();

                dep.Stop();
            }

        }

        public static void Changed(object sender, RecordChangedEventArgs<Product> e)
        {
            var changedEntity = e.Entity;

            Console.WriteLine("DML operation: " + e.ChangeType);
            Console.WriteLine("ID: " + changedEntity.ID);

        }
    }

**Comment by christiandelbianco** [comment]
Hi, the code is OK. Have you tried to execute the SQL script reported in Homepage's seciton "**Note about Compatibility Level and Database Version for tracking record changes**" ?

**Comment by TarrahArshad** [comment]
i need only know table changed and rowId i had before developed websocket and broker worked fine but for only know which row changed i see ur code but in simple console app not work

**Comment by TarrahArshad** [comment]
event change never fire all ur videos on youtube and sample code is same but why not work ?
my database is 11.0.6020 and .net is 4.6.1

**Comment by christiandelbianco** [comment]
Can you run the select described in "Note about Compatibility Level and Database Version for tracking record changes" ?
Then, does your model define any property matching a table column?
