### ISSUE TITLE
Where Use Case but the filter value coming from client.

### ISSUE THREAD

**Issue by aevi1103** [christiandelbianco/monitor-table-change-with-sqltabledependency#159]
Hi I have a filter related question:

- I know its possible to filter in the database changes using `ITableDependencyFilter filterExpression = new CustomSqlTableDependencyFilter(123);`

but this is me explicitly entering values to the filter, my question is it possible to pass the filter value on the client?

In my use case I have a bunch of clients and I only need to push notification on what machine are they in. I don't want them to see other notification from other machine... so I'm thinking if its possible to get the filter value and pass that value to the server?

**Comment by christiandelbianco** [comment]
If you want to have different filter for different client, you cannot use a single SqlTableDepdendency instance. You must have 1 SqlTableDepdendency for 1 client.
