### ISSUE TITLE
No support for .Net Core

### ISSUE THREAD

**Issue by slimeygecko** [christiandelbianco/monitor-table-change-with-sqltabledependency#16]
I get this error when I try to install this nuget package in my .Net Core project:

> Package SqlTableDependency 6.1.0 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package SqlTableDependency 6.1.0 supports: net (.NETFramework,Version=v0.0)

Are there any plans for this package to support .Net Core?

**Comment by christiandelbianco** [comment]
Not yet.

**Comment by christiandelbianco** [comment]
DONE
