### ISSUE TITLE
Exception thrown in SqlTableDependency_OnError

### ISSUE THREAD

**Issue by kanachrisi** [christiandelbianco/monitor-table-change-with-sqltabledependency#160]
Hello Christian,

I once got an exception thrown in SqlTableDepency_OnError, i don't know what caused, and i would like to know if you have some ideas of what is likely to cause it.
Thanks for the feedback and this wonderful plugin.

**Comment by christiandelbianco** [comment]
Hi, don't you have any message in the exeption from  SqlTableDepency_OnError?
