### ISSUE TITLE
Do you support bulk insert notification?

### ISSUE THREAD

**Issue by aevi1103** [christiandelbianco/monitor-table-change-with-sqltabledependency#162]
hello, do you support bulk insert notification? btw this tool is very useful thank you!

**Comment by christiandelbianco** [comment]
it should as a developer suggested how to solve this issue (bottom of home page):

_Deleting multiple records then inserting using sql bulk copy, only deleted change events are raised: to solve this problem, set SqlBulkCopyOptions.FireTriggers. Thanks to Ashraf Ghorabi!_
