### ISSUE TITLE
ALTER AUTHORIZATION

### ISSUE THREAD

**Issue by GreenDavidA** [christiandelbianco/monitor-table-change-with-sqltabledependency#164]
Hi,

I thought I'd post that I've been able to reliably get this working on databases that were created before SQL 2008 R2 by running the following command:

`ALTER AUTHORIZATION ON DATABASE::(database name here) TO sa;`

![image](https://user-images.githubusercontent.com/34946195/68241532-d8669400-ffdc-11e9-9bdf-57515797d83e.png)

I don't know if others will have the same success, but I thought I'd mention it.

Thanks,

David

**Comment by christiandelbianco** [comment]
thanks
i added your note: https://github.com/christiandelbianco/monitor-table-change-with-sqltabledependency/wiki/Contributors

regards

**Comment by christiandelbianco** [comment]
by he way, do you want i insert some info about you as i did for the other contributors?
