### ISSUE TITLE
Fire event after stored procedure finishes executing.

### ISSUE THREAD

**Issue by Edgaras91** [christiandelbianco/monitor-table-change-with-sqltabledependency#165]
I have a stored procedure, that has a `BEGIN TRANSACTION` and `COMMIT`.

Is it possible to fire an event only after the stored procedure finished executing?

Scenario:
Have a `Deal` table that has `Status` column.
The stored procedure creates a Deal row with status 0
Then it updates that status from 0 to 1, 2, 3, 4, 5 and ends.
I want my listener to only fire an event when a new deal with status 3 is inserted/updated.

Doing an` if (status = 3)` would be a bad idea. as the end result of that "Deal" row is actualy status 5 and it should not be actioned.

**Comment by christiandelbianco** [comment]
Hi
you can use the filter. Have a look at:

https://github.com/christiandelbianco/monitor-table-change-with-sqltabledependency/wiki/Use-case:-Where-filter

Regards

**Comment by Edgaras91** [comment]
> 
> 
> Hi
> you can use the filter. Have a look at:
> 
> https://github.com/christiandelbianco/monitor-table-change-with-sqltabledependency/wiki/Use-case:-Where-filter
> 
> Regards

Thanks, I had a quick look at it.
Could you tell me roughly what my filterExpression would look like?

Again, I am receiving 1 insert and 4 update statements at this time without this filter.

Would I filter for "COMMIT" command?

**Comment by Edgaras91** [comment]
I've tested using that expression, implementing `ITableDependencyFilter`
I managed to capture the middle update query, when I wanted to capture only the end status (5)

**Comment by christiandelbianco** [comment]
> Again, I want to only get an event on the end result when stored procedure finished executing.
It is not possible.
