### ISSUE TITLE
TableDependency stopped working after some time

### ISSUE THREAD

**Issue by mahabirsingh-kis** [christiandelbianco/monitor-table-change-with-sqltabledependency#166]
Found that the trigger in SQL gets removed when "TableDependency stopped working" error is raised, thereby, stopping further updates to the frontend. Manual workaround for that is to reset IIS so that trigger is re-created. In the logs I found :

SqlTableDependency error occured in "" . OnError in Server XYZ,Database ABC,Error ,The conversation handle "88E2B222-AE0A-EA11-9116-005056A469F8" is not found.

**Comment by christiandelbianco** [comment]
Hi,
can you supply me steps to reproduce this problem?
