### ISSUE TITLE
How to subscribe to changes witout knowing table structure/schema?

### ISSUE THREAD

**Issue by malichishti** [christiandelbianco/monitor-table-change-with-sqltabledependency#167]
HI,

I would like to know if there is a way to listen for changes on a Table for which one doesnt know the colums prehand. i.e. there is no Entity class to go with.

Right now  SqlTableDependency requires a T type.

Regards,
Ali

**Comment by christiandelbianco** [comment]
Hi, is not possible. At least one table column is required (for example [Id]).
