### ISSUE TITLE
OnChanged event not firing

### ISSUE THREAD

**Issue by frederikrj** [christiandelbianco/monitor-table-change-with-sqltabledependency#168]
Hi Christian.
I'm having an issue with your package that I cant quite figure out. I have tried following your example but and cannot get it to work.
When I change something in my database the OnChanged event doesn't fire.
I have had normal SqlDependencies work when data changes, but I need to know what the data that changed was, therefor I wanted to try your solution out.

Below is the class that I have implemented following your example. Hope you can help me out, thank you in advance

namespace RDSOnline.Data.Services
{
    public class DatabaseMonitorService : IDatabaseMonitorService
    {
        readonly string ConnectionString = "Data Source=[SERVER];Initial Catalog=[NAME];User ID=[USER];Password=[PASSWORD]";

        public DatabaseMonitorService()
        {
            StartService();
        }

        private void StartService()
        {
            ListenForChanges();
        }
        private void ListenForChanges()
        {
            using (SqlTableDependency<Code> dep = new SqlTableDependency<Code>(ConnectionString, "Codes"))
            {
                dep.OnChanged += OnDependencyChange;
                dep.OnError += (sender, args) => Console.WriteLine($"Error: {args.Message}");
                dep.Start();
            }
        }

        public static void OnDependencyChange(object sender, RecordChangedEventArgs<Code> e)
        {
            var dependencyChanged = e.Entity.Description;
        }
        ~DatabaseMonitorService()
        {
            SqlDependency.Stop(ConnectionString);
        }
    }
}

**Comment by christiandelbianco** [comment]
Hi,
SqlTableDependency implement **IDisposable** interface. This means that when the execution go out of the using statement, SqlTableDependency invoke dispose method and remove any database opbject created to send notifications. That is wky you do not get any record change notification.

**Comment by frederikrj** [comment]
Complete oversight from me.
Thank you very much for the quick response, much appreciated!!

**Comment by christiandelbianco** [comment]
You are welcome.

Check some real user cases in section **Monitor record table change examples and use cases** present in home page.
