### ISSUE TITLE
Hi christiandelbianco

### ISSUE THREAD

**Issue by kkehinde** [christiandelbianco/monitor-table-change-with-sqltabledependency#169]
![example](https://user-images.githubusercontent.com/55736300/70393115-e5f9aa00-19de-11ea-9c10-50c0fb013398.png)
I am using **SqlTableDependency** version 8.5.4 in WebAPI which is hosted in IIS. I enabled Application Initialisation Module, I set StartMode = **always running**, and **preload enable = true**. This creates multiple triggers, multiple stored procedures, and of course multiple active queues. As a result multiple events get fire when an update or insert occurs.

The idea is to make the service available without timing out. It works every time iis app pool recycles, it causes web-api to reload, a new instance of service broker objects are created.

Question:
Is there any solution to check if the service is running, or not. If not running to always drop all objects before creating new one?

**Comment by christiandelbianco** [comment]
Hi, in case you do **not** Dispose() sqltabledependency, db objects are automatically removed after 3 minutes. 

Is SqlTableDependency wrapped in a singleton instance?

SqlTableDependency has an enum property called Status.

**Comment by kkehinde** [comment]
Any sample code will be helpful.
Here snippets of my implementation below:

![image](https://user-images.githubusercontent.com/55736300/70393694-8d2d1000-19e4-11ea-9e86-3aba8369d814.png)

![image](https://user-images.githubusercontent.com/55736300/70393715-d1201500-19e4-11ea-85dc-ca5ac74bcc36.png)

![image](https://user-images.githubusercontent.com/55736300/70393745-396ef680-19e5-11ea-9cb1-f5ff8f0dda70.png)

When the webapi refereshes, I lost the status...Could you give me example of the snippet of using SqlTableDependency in Singleton instance, please?. The implementation class that wraps around the sqltabledependency class is within singleton instances.

**Comment by christiandelbianco** [comment]
You can find how i manage a single instance of SqlTableDependency in the following examples:

- https://github.com/christiandelbianco/monitor-table-change-with-mvc-signalR-jquery-sqltabledependency-example
- https://github.com/christiandelbianco/blazor-notification-db-record-change
- https://github.com/christiandelbianco/monitor-table-change-with-WPF-WCF-sqltabledependency-example

**Comment by kkehinde** [comment]
Thank you @christiandelbianco .
