### ISSUE TITLE
edit: Use with existing EF Core 2.0 DbContext

### ISSUE THREAD

**Issue by SwartHack** [christiandelbianco/monitor-table-change-with-sqltabledependency#17]
Hey Christian,
I really love how this looks. I think I got a proj with all the current versions, but I get this error from PM:

> Warning	NU1701	Package 'SqlTableDependency 6.1.0' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project.

Also wondering on an approach to use the connection string or connection from existing DbContext? I pull the connection string from my config:

`using (var dep = new SqlTableDependency<DwsFileExt>(config.GetConnectionString("DwsConnection"), "DwsFiles", mapper))
`
And I get an Exception message in my OutPut:

> Exception thrown: 'TableDependency.SqlClient.Exceptions.UserWithNoPermissionException' in TableDependency.SqlClient.dll
> An exception of type 'TableDependency.SqlClient.Exceptions.UserWithNoPermissionException' occurred in TableDependency.SqlClient.dll but was not handled in user code
> User without permissions.

I'm working on implementing in a EF Repository and will happy share my results if I can get it all working.

Thanks,
Eric

**Comment by SwartHack** [comment]
Edit: so not sure on the package version conflict. Everything compiles! Problem still persists for connection string and your implementation of SqlClient.

```
string connstring = FileContext.Database.GetDbConnection().ConnectionString;
string connstring2 = config.GetConnectionString("DwsConnection");
```
both of these return the same message, "User without permissions"...

Thanks for any insight

**Comment by christiandelbianco** [comment]
there is no solution. As specified in home page connection string user must be dbowner or have those GRANT permissions:

    ALTER
    CONNECT
    CONTROL
    CREATE CONTRACT
    CREATE MESSAGE TYPE
    CREATE PROCEDURE
    CREATE QUEUE
    CREATE SERVICE
    EXECUTE
    SELECT
    SUBSCRIBE QUERY NOTIFICATIONS
    VIEW DATABASE STATE
    VIEW DEFINITION
