### ISSUE TITLE
SqlTableDependency to a table with schema

### ISSUE THREAD

**Issue by haftado3** [christiandelbianco/monitor-table-change-with-sqltabledependency#171]
`var dep = new SqlTableDependency<PBase>(con, "P_Schema.PBase");`
it cant find the table inside schemas

**Comment by christiandelbianco** [comment]
if you have pent 5 minutes to read the documentation....

https://github.com/christiandelbianco/monitor-table-change-with-sqltabledependency/wiki/Use-case:-Explicit-database-table-name
