### ISSUE TITLE
Impact on DB Performance

### ISSUE THREAD

**Issue by smartaquarius10** [christiandelbianco/monitor-table-change-with-sqltabledependency#173]
I am building a web api which I'll host in azure.  DB's are also made in azure. I shall use the sql table dependency to closely monitor the change in one table because there are 350 end users who are requesting the  changes(only insert/update) into the table from a separate website. However, they are not regular like in last month only 50 times the updates have been done. But, due to this I can only close the listener in Application_End which means when API shutdown as the change can be requested any time 24/7. 

Does this make any any performance hit on the DB in production environment. Kindly suggest.

**Comment by christiandelbianco** [comment]
It is perfectly OK close or dipose SqlTableDEpendency on Application_End.
