### ISSUE TITLE
Is it possible to monitor specific row or cell?

### ISSUE THREAD

**Issue by smartaquarius10** [christiandelbianco/monitor-table-change-with-sqltabledependency#178]
Hello,

I have a case where I want to put trigger on specific cell value. For eg. a job will create through some user and those were specific user. After this, we need to fire trigger only after update of end time of the job. But we need to put trigger only on such type of jobs because there are other jobs as well who are in control of other automation software.

**Comment by christiandelbianco** [comment]
what is available is this:
- https://github.com/christiandelbianco/monitor-table-change-with-sqltabledependency/wiki/Use-case:-Where-filter
- https://github.com/christiandelbianco/monitor-table-change-with-sqltabledependency/wiki/Use-case:-Specify-for-which-properties-we-want-receive-notification-using-UpdateOfModel-T--mapper
- https://github.com/christiandelbianco/monitor-table-change-with-sqltabledependency/wiki/Use-case:-Filter-notification-by-change-type
