### ISSUE TITLE
Events raised in wrong order when using database transactions

### ISSUE THREAD

**Issue by maurei** [christiandelbianco/monitor-table-change-with-sqltabledependency#179]
# Issue
Events are fired in wrong order when wrapping sql statements in a database transaction.

# Details
Consider two subscriptions on `TableX` and `TableY`:
```c#
var subscriptionX = new SqlTableDependency<TableX>(connection);
var subscriptionY = new SqlTableDependency<TableY>(connection);
subscriptionX.OnChanged += (_, _) => { Console.WriteLine( "table X") }
subscriptionX.Start();
subscriptionY.OnChanged += (_, _) => { Console.WriteLine( "table Y") }
subscriptionY.Start();
```

Now check out the following query:
```sql
INSERT INTO TableX (Id) values (1)
INSERT INTO TableY (Id) values (2)
```
The order of raised events will be (as expected)
```bash:
table X
table Y
```

However if we wrap these statements in a transaction
```sql
BEGIN TRANSACTION
INSERT INTO TableX (Id) values (1)
INSERT INTO TableY (Id) values (2)
COMMIT;
```
the order of the events being raised is **reversed**
```bash:
table Y
table X
```

(Note that if two statements are done for *the same table*, order is preserved again. So it feels like sort of a race condition with the queues?).

# Relevance
I think this is a bug because I don't think it reflects the order in which MSSQL publishes the notifications. The broker instead raises them as X and Y, like when there is no transaction.

This is a problem for me because I'm syncing two databases and it crashes because of this. In my case X is eg. `Article` and Y is `ArticleTag` (join table many-to-many).  If `ArticleTag` is propagated before `Article`, the system which is consuming the events will be looking for a `Article` that does not exist yet (because the corresponding create event is received only after the create event of the joint table record).

**Comment by christiandelbianco** [comment]
Hi. Understand the problem. However, I do not think that i can do anything, because the two instances of SqlTableDependency are on two different C# **threads**. Also, because we have two SqlTableDependency  instances, we also have two different service brokers (one for each SqlTableDependency)

**Comment by maurei** [comment]
Yeah I can imagine having independent instances/threads making this bug hard to deal. Also because you probably want to stay away as much as possible from any coupling between different threads/instances. 

However, the order in which these events are received in my example above is **consistently reversed**. I would have expected it to be random if it purely was a concurrency/async issue. And because of that I have the feeling there must be a work around? I tried playing around with the order of creating the SqlTableDepdendency instances (first `X` then `Y` and swapped) but the event order remains invariant under that.

I'm planning on doing a deep dive into this matter with my colleague, but I hope you could help us out with some preparatory work.

**Comment by maurei** [comment]
Yeah I can imagine having independent instances/threads making this bug hard to deal with. Also because you probably want to stay away as much as possible from any coupling between different threads/instances. 

However, the order in which these events are received in my example above is **consistently reversed**. I would have expected it to be random if it purely was a concurrency/async issue. But there seems to be some mechanism that is consistently swapping the order and because of that I have the feeling there must be a fix/work around? 

I tried playing around with the order of creating the SqlTableDepdendency instances (first `X` then `Y` and swapped) but the event order remains invariant under that.

I'm planning on doing a deep dive into this matter with my colleague, but I hope you could help us out with some preparatory work.

**Comment by christiandelbianco** [comment]
I just tested following your example.
For me, with TRANSACTION, works as expected.
Ten minutes and i will send you a video

**Comment by christiandelbianco** [comment]
as you can see from the video, i run sqltabledependency and then i modify manually the trigeers, in order to add an INSERT statement in a simple LOGGING table. The order in that table respect the order expected: this means that the trigger X is executed before tigger Y.
However, the console result show, from time to time, not the correct order. This is because of c# thread. 

I will attach the link to test video in 5 minutes

**Comment by christiandelbianco** [comment]
Video: [https://gofile.io/?c=QN47cM](https://gofile.io/?c=QN47cM)

Modify the two SqlTableDependency triggers adding this at the beginning:

Trigger for table X:
```
	INSERT INTO [dbo].[WhoFirst]
           ([Message])
     VALUES
           ('TableX')
```

Trigger for table Y:
```
INSERT INTO [dbo].[WhoFirst]
           ([Message])
     VALUES
           ('TableY')
```

**Comment by christiandelbianco** [comment]
```
SELECT TOP (1000) [Message]
  FROM [SQLTABLEDEPENDENCY].[dbo].[WhoFirst]
```
Result:
TableX
TableY
TableX
TableY

**Comment by maurei** [comment]
> The order in that table respect the order expected: this means that the trigger X is executed before tigger Y. 
> However, the console result show, from time to time, not the correct order. This is because of c# thread.

It seems you're right: even though I haven't been able to get it in the expected order, you've pretty clearly demonstrated it indeed is not consistent, i.e. it is a concurrency issue.

How feasible would it be to support monitoring multiple tables from one thread to ensure output consistency in cases like these? Would that require a massive overhaul?

Thanks for your efforts so far 👍

**Comment by christiandelbianco** [comment]
> How feasible would it be to support monitoring multiple tables from one thread to ensure output consistency in cases like these? Would that require a massive overhaul?

It must change completely the code.
