### ISSUE TITLE
Problem with double type column

### ISSUE THREAD

**Issue by TitoCalleros** [christiandelbianco/monitor-table-change-with-sqltabledependency#18]
I have a problem with a double type column (this column stores a datetime as an SQL Format), when the insert was reported, the value was truncate to only 2 decimal digits.

**Comment by TitoCalleros** [comment]
I was looking at code, and I asume the main cause of this problem is in RecordChangedEventArgs, in GetValueObject(PropertyInfo propertyInfo, string value), becuase it uses the CultureInfo for the conversion (return Double.Parse(value, this.Culture);, but I don't know where change this configuration only for SqlTableDependency.

**Comment by christiandelbianco** [comment]
Hi, there is a property

**Comment by TitoCalleros** [comment]
Hi, sorry for respond until now, 

I think that this doesn't resolve my problem, My database has a double column with at least 10 decimals, and there isn´t a culture info with this configuration.

**Comment by TitoCalleros** [comment]
Hi, thanks for reopen this issue. What do you think of create an inexistent culture info (maybe an "xx-xx") and in the switch of the GetValueObject function replace return Double.Parse(value, this.Culture) with a function like this:

private ConvertDoubleValueObject(string value, string cultureInfo)
{
    if (cultureInfo == "xx-xx")
        return Double.Parse(value);
    return Double.Parse(value, this.CultureInfo);
}

**Comment by christiandelbianco** [comment]
Sound a good idea.
Just one thing: can you download source code, apply your fix and run all integration tests?
If all if fine, i integrate your fix

**Comment by christiandelbianco** [comment]
Hi.
I change the property 
public string CultureInfoFiveLettersIsoCode { get; set; } = "en-US";

to 
**public CultureInfo CultureInfo{ get; set; };**

Now, setting the .NumberFormat of the specified culture info, you should be able to set number of decimals.

**Comment by TitoCalleros** [comment]
Hi Christian,

I was testing this upgrade, and i observe the same behavior, 

                var mapper = new ModelToTableMapper<EventoGIL>();
                var updateOfModel = new UpdateOfModel<EventoGIL>();
                var cuInfo = new System.Globalization.CultureInfo("es-mx");

                Dependency = new SqlTableDependency<EventoGIL>(Conexion, Tabla, null, null, ColumnasMapeadas, null, DmlTriggerType.All);
                cuInfo.NumberFormat.NumberDecimalDigits = 10;
                cuInfo.NumberFormat.CurrencyDecimalDigits = 10;
                cuInfo.NumberFormat.PercentDecimalDigits = 10;
                Dependency.CultureInfo = cuInfo;

In my Database, I have this records:
![image](https://user-images.githubusercontent.com/30841574/40627588-787f4726-6285-11e8-8c67-47ac1ba71a62.png)

The column FechaHora is my problem, because when I recieved the changed record, I receive only this:  
![image](https://user-images.githubusercontent.com/30841574/40627673-ea5c35f2-6285-11e8-918f-3ea8bfc7ba43.png)

So, I think the problem is not in 
 protected virtual object GetValueObject(PropertyInfo propertyInfo, string value){}

I think the problem could be generated from the MessageBag received. 

I was checking your CultureInfoTest, but it only test for DateTimeFormat, but it doesn't test for single or double type columns.

**Comment by TitoCalleros** [comment]
I confirm that is not only a problem with the cultureInfo. I changed GetValueObject(PropertyInfo propertyInfo, string value) function, removing cultureInfo for single, double and decimal column, and the problem continue:

  case TypeCode.Single:
                    return float.Parse(value);
                //return float.Parse(value, base.CultureInfo);

                case TypeCode.Double:
                    return double.Parse(value);
                    //return double.Parse(value, base.CultureInfo);

                case TypeCode.Decimal:
                    return decimal.Parse(value);
                    //return decimal.Parse(value, base.CultureInfo);

![image](https://user-images.githubusercontent.com/30841574/40629219-55fed45a-628f-11e8-82d8-1f6cd8ff823c.png)

I recieve this value: 
![image](https://user-images.githubusercontent.com/30841574/40629239-789137ec-628f-11e8-98e7-5a85b0005c93.png)

Do you have any idea where is the problem?

**Comment by christiandelbianco** [comment]
working on

**Comment by christiandelbianco** [comment]
I have checked. As you can see from this [video](https://ufile.io/te4ja), all works fine for me.

Can you send me the script for creating your table and a zip file containing a solution that reproduce this error?

Regards

**Comment by christiandelbianco** [comment]
It should be fixed.

Assuming your table is:

![2018-05-30 at 15-11-30](https://user-images.githubusercontent.com/13263017/40722935-f01320e8-641d-11e8-90da-6915de1b7dce.png)

![2018-05-30 at 15-11-59](https://user-images.githubusercontent.com/13263017/40722939-f3e2228c-641d-11e8-99a3-d2387771161f.png)

Your C# model property mapping FLOAT table column, must be a decimal:

![2018-05-30 at 15-13-37](https://user-images.githubusercontent.com/13263017/40722953-fc75c43a-641d-11e8-8dfa-43e78836a694.png)

I get:

![2018-05-30 at 15-14-44](https://user-images.githubusercontent.com/13263017/40722969-0518ed38-641e-11e8-825c-90c3f8a5906d.png)

Fix available with version **7.4.0**.

**Comment by christiandelbianco** [comment]
As soon as integration test finish, i will be publich version 7.4.0
