### ISSUE TITLE
Catch up on missed changes while application was not running?

### ISSUE THREAD

**Issue by RudeySH** [christiandelbianco/monitor-table-change-with-sqltabledependency#180]
Is it possible to get notifications on start-up from changes that happened while my application was not running? I'm implementing an application which needs the guarantee that all changes are captured, but every time the application restarts it runs the risk of missing changes.

**Comment by christiandelbianco** [comment]
> Is it possible to get notifications on start-up from changes that happened while my application was not running?
No, is not possible.
