### ISSUE TITLE
database compatability issue - See How David Green Solved This Problem

### ISSUE THREAD

**Issue by hbrof** [christiandelbianco/monitor-table-change-with-sqltabledependency#182]
Hi,

 I went and ran the query regarding the database version. and in the db where it is not working, we have a db create version of sql 2005. I guess now it makes some sense.  I tried to follow the link reference for David Green's solution, it doesn't find anything from David Green. Is there a way to update the database create version or another way to resolve this issue?

thanks
harvey

**Comment by christiandelbianco** [comment]
I have no idea.
Sorry

**Comment by GreenDavidA** [comment]
@hbrof https://github.com/christiandelbianco/monitor-table-change-with-sqltabledependency/issues/164

**Comment by hbrof** [comment]
Thanks. So for us, the thing that worked was ownership. 

Turns out that when you copy, move or restore a database to another server, the users and permissions do not map as one assumes. In fact, {OurDBUser} did not have the privileges to do the various things necessary in the database including cleaning up after itself related to the dependency functions. I have some documentation from Microsoft for future reference and am waiting on a set of minimum necessary privileges for best practices so turning everyone into an sa level isn't the ultimate answer. Bottom line, even though an id may be mapped from the server to the database, it may not have the permissions assumed.

Harvey
