### ISSUE TITLE
clean up sp's not fully functioning

### ISSUE THREAD

**Issue by hbrof** [christiandelbianco/monitor-table-change-with-sqltabledependency#183]
I am trying to find out why the clean up sp's are not doing their job on our server. Why would

IF EXISTS (SELECT * FROM sys.service_contracts WITH (NOLOCK) WHERE name = N'dbo_Customers_0950774a-3c90-49e3-af6c-dd8344d4a8a4') DROP CONTRACT [dbo_Customers_0950774a-3c90-49e3-af6c-dd8344d4a8a4];

do nothing, and then cause the rest of the script to also do nothing due to the contract being in place

but just doing

DROP CONTRACT [dbo_Customers_0950774a-3c90-49e3-af6c-dd8344d4a8a4];

work?

thanks
Harvey

**Comment by christiandelbianco** [comment]
DROP CONTRACT [dbo_Customers_0950774a-3c90-49e3-af6c-dd8344d4a8a4]; it will works

**Comment by hbrof** [comment]
yes, it works by itself, but for some reason, as I was trying to see why so many of these were on the server, the if statement fails, and the drop statement doesn't happen which prevents the removal of anything that depends on the contract being dropped. Do you know if there is some permission thing or somthing that would cause the if statement on the contract to fail?

**Comment by christiandelbianco** [comment]
Probably is is because this missing the clause **WITH EXECUTE AS SELF** in the stored procedure definition. As this is a bug, i will prepare a new NuGet package for that.

**Comment by christiandelbianco** [comment]
Fix with release 8.5.8
