### ISSUE TITLE
Attaching to existing queues

### ISSUE THREAD

**Issue by JamesT-W** [christiandelbianco/monitor-table-change-with-sqltabledependency#185]
Hello Christian,

I left a comment on an old issue https://github.com/christiandelbianco/monitor-table-change-with-sqltabledependency/issues/22 however I'm not sure if you will have seen that as the issue is closed.

My scenario is that if all services that are running the SqlTableDependency go down, when they start back up we can no longer connect to the queue (as it creates a new guid in the queue name each time) and instead connect to a new queue. However, the old queue may have still been queuing up table changes, therefore we will miss responding to these table changes.

You mentioned about changing our code to pass as parameter the queue name (in issue 22 that I have linked). Could you explain in detail how to achieve this, ie. What needs changing in our code? Does any of your code need changing? Where is your config file located? Do we need to call a specific method that accepts the queue name?

Kind regard,
James.

**Comment by christiandelbianco** [comment]
> Could you explain in detail how to achieve this
It is a huge change, and cannot be explained in 3 words.
Sorry.

**Comment by christiandelbianco** [comment]
there is an extension **not** done by me:
[https://github.com/tomasfabian/SqlTableDependency.Extensions](https://github.com/tomasfabian/SqlTableDependency.Extensions)

**Comment by tomasfabian** [comment]
Hi **@JamesT-W** ,
in the past I released a SqlTableDependency extension package which enables re-connections without preserving existing database objects or conversation handlers.
Nowadays I'm working on a reconnection logic which tries to reuse an existing conversation, if it wasn't timeouted. 
Please try the preview version and let me know if there are any issues.
https://www.nuget.org/packages/SqlTableDependency.Extensions/1.1.0-beta2

Thank you **@christiandelbianco** for your support.

Tomas

**Comment by JamesT-W** [comment]
Hi @christiandelbianco 

Thanks for the response and the suggestion of Tomas' extension, I went off looking at it and forgot to come back and thank you!

Thanks, James

**Comment by JamesT-W** [comment]
Hi @tomasfabian ,

That's great, thanks for the response. I'll take a look at the preview version tomorrow and let you know if I do find any issues, but I'll do it in your repository instead of here rather than in Christian's. 

Thanks, James
