### ISSUE TITLE
Objects(Message Types, StoreProcedures, Queue etc) which are created are not getting cleared in the 

### ISSUE THREAD

**Issue by Suresh9sb** [christiandelbianco/monitor-table-change-with-sqltabledependency#186]
Hi Christian,

I see in my database, objects are getting filed up and not getting cleared which are created under 
Programmability -> Stored Procedures -> 
Service Broker ->Message Types 
                        -> Contracts
                        -> Queues
                        -> Services etc. 
These objects are created on a table and system is working fine.

So want to know, is there any way to identify and clean objects which no longer required ? 

or if there is any procedure to handle please do let me know.

Thanks 
Suresh

**Comment by christiandelbianco** [comment]
SqlTableDependency's database objects are removed immediately when .Dispose() is called OR after 3 minutes. I would suggest you to download the source code solution, and run all the tests (you must change connection string). You will see that once all tests are completed, every SqlTableDependency's database object is removed.
