### ISSUE TITLE
Trigger blocks  DML operations

### ISSUE THREAD

**Issue by gorden1991** [christiandelbianco/monitor-table-change-with-sqltabledependency#190]
Hello , i deploy a program as a windows service, and if i reboot computer ,the trigger will not delete,and will blockgs DML operations.how can i fix it ,thanks

**Comment by christiandelbianco** [comment]
Do you think you give me enough info to guess what is the problem?

**Comment by gorden1991** [comment]
um.soryy .
i declare a tableDependency object like this .
var _tableDependency = new SqlTableDependency<T>(tcitClinetConn, "tableName", "schemaName",);
step1. when the program start i call _tableDependency.Start() .  there will be a table trigger.
step2.  i reboot computer,so _tableDependency.Stop() can not be called 
step3.  i run the program again .there will be anothor table trigger.  
so  i want to konw how can i clear the redundant tigger and something  on Service Broker.
did I explain it clear？ thanks for you patient.

**Comment by christiandelbianco** [comment]
"step3. i run the program again .there will be anothor table trigger." this is normal: Sql Table Dependency is not a permanent Queue. 

Regarding "so i want to konw how can i clear the redundant tigger and something on Service Broker." SqlTableDependency has a _watch dog_ that after 3 minutes dispose the Triggers, queue and service broker. If you rebot the server, this watch dog is reset and it cannot anymore remove the SqlTAbleDependency objects. Sorry, You must do by your self.

**Comment by gorden1991** [comment]
I read your code and problem solved，thanks.

**Comment by christiandelbianco** [comment]
it would be nice if you describe what was the problem, in order to help other users in case they have same issue. Thanks
