### ISSUE TITLE
Cannot create DB objects 

### ISSUE THREAD

**Issue by 93Kamuran** [christiandelbianco/monitor-table-change-with-sqltabledependency#194]
I have an Asp.net Web API project that is using entity framework DB first integration. I want to use sqltabledependency with signalr to take my realtime data from Database.  When I fallow your Knockout js example on my server, Everything works well I created your example DB and run the project. sqldependency DB objects created and taked data notification. However when I try to create a new project and connect with my DB which is using my main project with entity framework. Dependency project  runs. There is no Error but DB objects did not be created. So  I could not get any notification. 

I Also enabled service brokers and make the user   using on connection string is db_owner
Could you please help me ?

**Comment by christiandelbianco** [comment]
Follow - step by step - the example in the home page (https://github.com/christiandelbianco/monitor-table-change-with-sqltabledependency) to build up a console app. If, for any change you do in DB receive a notification, then the problem for YOUR web app, is in your code.

**Comment by 93Kamuran** [comment]
I can start the example on the home page on my DB. But why ı cannot use sqltabledependency like your knockout js example? 
 this.SqlTableDependency.OnChanged += this.TableDependency_OnChanged;
never fires
