### ISSUE TITLE
reduce amount of time before deleting create objects

### ISSUE THREAD

**Issue by csafg2** [christiandelbianco/monitor-table-change-with-sqltabledependency#20]
is there a configuration to specify amount of time before execution of cleanup SP.
the time out is a bit problematic because in some cases if the receiver application is down, detecting that might be impossible for database code.

**Comment by swASO** [comment]
hey, 
i think you are searching for the **watchDog** parameter on **Start** Method of the SqlTableDependency

> Start(int timeOut = 120, int watchDogTimeOut = 180)
