### ISSUE TITLE
No trigger for certain Colum

### ISSUE THREAD

**Issue by Abbas111977** [christiandelbianco/monitor-table-change-with-sqltabledependency#211]
Hello, 
            After changing Colum name, the change in this Colum is not trigger the handler any more !!!
how can I fix this issue ?
thanks in advance

**Comment by christiandelbianco** [comment]
Of course you do not get trigger any more!!!!!!!!!
The stored procedure credated is still tergetting the old column name.
stop and restaret SqlTableDepenmdency
