### ISSUE TITLE
Table name not found for tables with multiple period (.) characters

### ISSUE THREAD

**Issue by jazzeser** [christiandelbianco/monitor-table-change-with-sqltabledependency#24]
I'm having trouble with using the sqltabledependency for tables that have at least one period (.) character on them i.e. "**_[dbo].[Stream.Users]_**". It seems that you're splitting the table name and only getting the string on the first index of the split array as the table name based on the code.

**Comment by christiandelbianco** [comment]
Working on...

**Comment by christiandelbianco** [comment]
Fixed in version 6.**2**.0.0

**Comment by christiandelbianco** [comment]
Hi,
It should works simply using following code:

    **[Table("Stream.Users")]**
    public class StreamUsers

    ....

    var dep = new SqlTableDependency<StreamUsers>(connectionString)


have a look at: https://github.com/christiandelbianco/monitor-table-change-with-sqltabledependency/wiki/Use-case:-Code-First-Data-Annotations-to-map-model-with-database-table
