### ISSUE TITLE
On Change not getting fired after some time

### ISSUE THREAD

**Issue by sacOO7** [christiandelbianco/monitor-table-change-with-sqltabledependency#25]
After adding data in the monitored table, change in data is reflected in the event handler. But, after time of 2- 3 hrs, it stops working. I think problem might be due to lock on queue due to activation procedure. No data change is received, even though I add records on server side table. I can see queue filled with records but no change at client side. It keeps saying
`Running waitfor command `
after 2 mins timeout.
Can you help me with this? It is really necessary.

**Comment by christiandelbianco** [comment]
Hi.
I will help you with pleasure. However, I also need your help too.
Have you any "test case" that i can use to **reproduce** this issue. Unfortunately I never had this problem.

**Comment by sacOO7** [comment]
Hi christiandelbianco, sorry for the late reply. I was able to recreate the issue. Seems like issue is in the trigger. It is getting deleted after some random time. So, it is not able to insert any data inside queue and thus at the client side, no data is received even though new records are being added. Due to confidentiality of the project, I cannot post any screenshots, but I think issue is due to activation procedure (cleanup procedure) on the queue. It gets called for every record being added. Maybe it is deleting the trigger somehow, which is not supposed to happen. It will be really helpful if you can resolve the issue.

**Comment by christiandelbianco** [comment]
Hi.
"_Seems like issue is in the trigger. It is getting deleted after some random time_" usually this happen when you code is paused: for example you have a windows service that is paused or the server where your code is running is put in sleep mode. Do you have something like that?

**Comment by sacOO7** [comment]
Actually all other database objects are present. but, trigger is getting deleted. If that is the case, where server is in sleep mode, then conversation dialogue is supposed to destroy all objects from the service broker. This doesn't seems to be the case. Only trigger is getting deleted.

**Comment by dengxuesong** [comment]
I have the same problem, my condition is  that i put the sqltabledependency in one service, but after some hours my computer has sleeped, and then i awaken my computer ,the sqltabledependency no longer listener the sql changed.

**Comment by christiandelbianco** [comment]
@ dengxuesong: "but after some hours my computer has sleeped". This is why SQL TableDependency objects are disposed.
