### ISSUE TITLE
ASP.NET

### ISSUE THREAD

**Issue by ErikvdBurgwal** [christiandelbianco/monitor-table-change-with-sqltabledependency#26]
Hi,

I created an asp.net application (w/ SignalR) that monitors a table. It all works fine, but in production, I see that the database triggers etc get cleared after some time. This may be related to the fact that IIS automatically suspends worker-processes after some idle time.

Do you have a suggestion which configuration / settings can be used in order to ensure that the SqlTableDependency will remain 'active', or resume? 

Thanks,
Erik

**Comment by christiandelbianco** [comment]
> This may be related to the fact that IIS automatically suspends worker-processes after some idle time
Yes, this is the reason.
