### ISSUE TITLE
Encountered 2 Issues at Client side

### ISSUE THREAD

**Issue by chxxangie** [christiandelbianco/monitor-table-change-with-sqltabledependency#27]
I encountered two issue when try this solution. 

1. Client has not responded after sometimes even table has changes (insert/update/delete). I need to stop the application pool at the web service server then restart, then the client will be working fine again.
2. Client program exit with code -1 every time when i stop the client program running.

Can you please help to advise where is going wrong? I followed the code in your website and has minor modification (eg table, connection string, etc). And also I change to simple window application instead of WPF application by writing the changes to the Debug output.

Thanks in advance! :)

p/s: wcf code and client code are attached as well.

[wcf_client.zip](https://github.com/christiandelbianco/monitor-table-change-with-sqltabledependency/files/1614115/wcf_client.zip)

**Comment by christiandelbianco** [comment]
Hi. I am not sure 100% but i think that your WCF service, even if if dedined as singleton, should not instantiate and keep a reference to SqlTableDependency. If i were you, i would create a SqlTableDependency instance in Global.asax.
