### ISSUE TITLE
Inbound disconnects not cleaned up

### ISSUE THREAD

**Issue by amoorthaemer** [christiandelbianco/monitor-table-change-with-sqltabledependency#30]
Hi!

I'm using your component for a while now and I noticed that inbound disconnects aren't cleaned up, which slowed down my SQL server almost to a grinding halt (+600.000 half open connections) I guess this has todo with the fact that the conversations aren't ended in a proper manner. When I took a look at the generated triggers a couple of things got my attention...
1) You don't use any transactions when sending messages
2) END CONVERSATION doesn't include WITH CLEANUP

I guess that the latter is the culprit.

TIA
Bert

**Comment by christiandelbianco** [comment]
Hi.
Can you tell me which version are you using? In the last one 6.1.0.0?
