### ISSUE TITLE
Exception when a table name is keyword

### ISSUE THREAD

**Issue by fltimes** [christiandelbianco/monitor-table-change-with-sqltabledependency#32]
I have a client with a table named "Transaction.Header" and "Transaction.Item".  I create my dependency with 
 _tableDependency = new SqlTableDependency<T>(ConnectionString, TableName);
 _tableDependency.Start();

Where TableName is "Transaction.Header" or "Transaction.Item". The exception occurs on Start()
System.Data.SqlClient.SqlException, Incorrect syntax near the keyword 'Transaction'.

Note I've tried the string "[Transaction].[Header]" and that also does not work. I see in your code you remove the []. Possibly they should not be removed?

**Comment by fltimes** [comment]
I also tried that solution and I get a different exception all the time: TableDependency.Exceptions.NotExistingTableException: 'I cannot find a database table named '[Routing].[Round]'.'
My class is
   [Table("Transaction.Header")]
    public class TransactionHeaderModel
    {
        public Guid TransactionHeaderId { get; set; }
        ....
     }

and I create with
_tableDependency = new SqlTableDependency<TransactionHeaderModel>(ConnectionString);

Note I get this exception even with another table name "Routing.Round". I've opened the connection string and verified all the tables are there. I've also tried strings "Routing.Round", "[Routing].[Round]" and neither worked.

**Comment by christiandelbianco** [comment]
HI.
I am able to reproduce this issue using same table naming you used.
Working on it

**Comment by christiandelbianco** [comment]
Hi ...sorry but i still cannot reproduce the error. Using same table names, this is what 

```
namespace ConsoleApplicationSqlServer
{
    [Table("Transaction.Header")]
    public class Customer
    {
        public int Id { get; set; }
        public string CompanyName { get; set; }
...
....

 using (var dep = new SqlTableDependency<Customer>(connectionString))
            {
                dep.OnChanged += Changed;
                dep.OnError += OnError;
                dep.Start();

                Console.WriteLine();
                Console.WriteLine(@"Waiting for receiving notifications...");
                Console.WriteLine(@"Press a key to stop");
                Console.ReadKey();
            }

```
In attached figures, you can see that TRIGGER is created ad i can receive notifications.
![2018-01-26 at 14-50-17](https://user-images.githubusercontent.com/13263017/35442825-e68c95bc-02a8-11e8-85e5-97a04b936bc2.png)

![2018-01-26 at 14-49-14](https://user-images.githubusercontent.com/13263017/35442717-83012b5c-02a8-11e8-9c92-dbd7474c5eb7.png)
