### ISSUE TITLE
Issue starting service with SQL 2008 (none R2)

### ISSUE THREAD

**Issue by Adz5156** [christiandelbianco/monitor-table-change-with-sqltabledependency#34]
Hi, I'm having an issue trying to implement this with an MVC application against a SQL 2008 database. However it looks like the command/hint POISON_MESSAGE_HANDLING ( [ STATUS = { ON | OFF } ) is not supported on this version. 

When the application tries to register the dependency it fails due to incorrect syntax. Is there anyway I can specify a parameter to exclude the poison message hint from the Queue create statement?

P.S. This is a great library, fantastic work!!

Many Thanks
Regards
Adam

**Comment by christiandelbianco** [comment]
Hi...

at least SQL 2008 **R2** database is needed.

**Comment by Adz5156** [comment]
It may be worth adding that to the requirements section on the read-me. A future development for robustness maybe to include a target version parameter to allow certain version gotchas to be accommodated. 

Thanks

**Comment by christiandelbianco** [comment]
You're right.
I update README file
Thanks.
