### ISSUE TITLE
Teardown Functionality

### ISSUE THREAD

**Issue by SteveYurka** [christiandelbianco/monitor-table-change-with-sqltabledependency#36]
I noticed that in release Release 5.0.0.0 the ability to prevent the teardown of database objects was added, however this feature seems to be gone in the latest release.

Is there any documentation on how to use this feature? Or was this feature removed in a later version and no longer supported now? 

Thanks heaps!

**Comment by christiandelbianco** [comment]
Hi, this feature was removed because of some bugs quite impossible to fix.
