### ISSUE TITLE
Hello, long time to say hello_my free customer reported he cannot receive notification any more after one day.

### ISSUE THREAD

**Issue by herurider** [christiandelbianco/monitor-table-change-with-sqltabledependency#37]
You might remember me in CodePlex as a Korean programmer(Kay Lee) with non-software related major.

In these days, Winter Olympic 2018 PyeongChang, Korea is taking place and hope your country's excellent achievements !

One of my free customer reported that suddenly, without any error message, he cannot receive notification any more from a few days ago after 2 other applications were updated as he remembers.

As you might know, it's very difficult to ask informations to some customers.

With very limited information like there was no error message, I assume the local SQL server was shut downed abnormally and some dependency objects were not removed automatically and interfering normal notification.

What I'd like to know are,

1)
When dependency objects are abnormally existing after abnormal shut down, (after turning off the computer(SQL server) and turning on at next day), what if SQLTableDependency is started and terminated normally? the previous, abnormally existing dependency objects will be removed automatically together?
(My customers turn on and off their computer(SQL server) everday.)

2)
Do the dependency objects have unique fingerprint in their name so that I can remove exact dependency objects only, not other objects by other applications?

Kind let me know the unique fingerprint if exists,

or I do appreciate if you provide the SQL code to remove dependency objects so that I can remove previously existing dependency objects for sure before customers start my application.
(Please kindly understand again that I'm a low level programmer with non-software related major.)

We're just finishing Lunar New Year Holidays and I'll try my best to communicate with the customer and check with various indirect ways like another SQL table and so on.

Sorry, I'm always too talkative, eager to solve my problem but sure it's very easy to answer.
(Many of my customers are still using SQL 2005, 2008, therefore, I must stay with old version of SQLTableDependency like 5.x.x.x)
(and my customers don't know about programming, software, SQL)

Always thank you so much for your excellent SQLTableDependency !

Sincerely,
Kay Lee.

**Comment by christiandelbianco** [comment]
Does the SERVER hosting SqlTabledependency go to SLEEP mode?

**Comment by herurider** [comment]
Hello, As I know, their server never go to SLEEP mode.

I've double-checked with another user and been confirmed the data-saving table is changed to another table. Now, everything is working fine :)

Because my application is sub-application, it has a destiny which must know how the Main Applications work.

Always my best appreciation to excellent SqlTableDependency !

**Comment by christiandelbianco** [comment]
Thanks,
So, as your wrote "Now, everything is working fine :)" i will close the BUG.
Have a nice day!
