### ISSUE TITLE
SqlTableDependency on Views

### ISSUE THREAD

**Issue by Flogex** [christiandelbianco/monitor-table-change-with-sqltabledependency#39]
Hey Christian,
I'm pretty new to SQL Server and databases in general.
I was wondering if it is possible to get SqlTableDependency to work with views instead of tables only. Currently it throws a _TableWithNoColumnsException_ if I try this out.
So do the triggers and the notification pipeline theoretically work with Views?

**Comment by christiandelbianco** [comment]
Hi
No, SqlTableDependency works only with TABLEs

**Comment by IlanAgenbacht** [comment]
Hi there,

Will this be possible in future release? Has this been considered?

**Comment by Flogex** [comment]
Hey,

if I remember correctly, SqlTableDependency uses AFTER triggers to create the notifications after DML statements were executed. But you can only use INSTEAD OF triggers on views (see [MS Docs](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-trigger-transact-sql?view=sql-server-2017#arguments)).

I am not a SQL expert, but I would say that it is not possible to implement the SqlTableDependency use case with INSTEAD OF triggers; hence it is not possible to use SqlTableDependency with views.

**Comment by christiandelbianco** [comment]
Sorry; there is no plan to make sqltabledependency to works with views.
