### ISSUE TITLE
Minimal SQL version requirement.

### ISSUE THREAD

**Issue by TimKras** [christiandelbianco/monitor-table-change-with-sqltabledependency#4]
I'm getting this error: "Incorrect syntax near 'POISON_MESSAGE_HANDLING'."
We are using SQL 2008 (no R2).

Is there a minimal SQL version requirement?

**Comment by christiandelbianco** [comment]
It should work with 2008 R2, but development was done using SQL Server 2012.
.NET Framework >= 4.5.1

**Comment by iamanandrajs** [comment]
what is the solution for this issue?

**Comment by christiandelbianco** [comment]
Hi...as i told you, it is needed 2008 **R2** at least
