### ISSUE TITLE
TearDown not available

### ISSUE THREAD

**Issue by jnallu** [christiandelbianco/monitor-table-change-with-sqltabledependency#40]
Hello,

I am trying to set the "teardown" to false so that objects are not removed every time service stops.
Does SqlTabledependancy support teardown functionality. It was mentioned in the release notes version 5 as a new feature. I looked at the code and don't see a constructor for tabledepenndancy  which takes teardown as parameter

**Comment by christiandelbianco** [comment]
Please, version 5 in totally out of date and with bugs. Please do not use, because there are situations that will bring issue to your DB.

**Comment by jnallu** [comment]
I am using version 6. Does version 6 support teardown?
I am trying to use a constructor like this 
new SqlTableDependency<TeardownTestSqlserver1Model>(ConnectionString, teardown: false);

**Comment by christiandelbianco** [comment]
Teardown has been removed

**Comment by jnallu** [comment]
Thanks  much!

**Comment by VineetSachan11** [comment]
So what is alternate  option for teardown?
Please clarify can i active connection all time .
