### ISSUE TITLE
Performance concerns using SqlTableDependency in a Windows Form application

### ISSUE THREAD

**Issue by disti** [christiandelbianco/monitor-table-change-with-sqltabledependency#41]
Hello,

We developed a Windows Forms booking system some years ago.
This application manages booking of hotel rooms associated with tours organized by our customer.
While making a  reservation, a map of all free rooms is shown to the user.
We developed the system so that while a user is booking a room for a certain tour, other users are not allowed to book on the same tour.
This is to avoid that two users occupy the same room.

This was acceptable when the system was used by emplyees only.
Now we're opening the booking system to Internet, using MVC, while keeping the Windows Forms application for reservations made by employees (WF App has some advanced functions not available to customers). 

In order to manage concurrency, we were evaluating SqlTableDependency, so that both WF App users and MVC users are notified as soon as a room gets occupied.

But we are wondering if this component can be safely used on many (10-15) windows clients monitoring the same table at the same time.

Thank you!

**Comment by christiandelbianco** [comment]
Well, what is important is that you have ONLY one class managing with SqlTableDependency. Please have a look to this example: https://github.com/christiandelbianco/Monitor-table-change-with-WPF-WCF-sqltabledependency. Here we have only one class (a WCF service) dealing with SqlTableDependency. 

SqlTableDependency notify the service that in turn notify 1,2,3 ect...listener classes.
