### ISSUE TITLE
Text column type is not an supported by SqlTableDependency

### ISSUE THREAD

**Issue by EdmundoCoate** [christiandelbianco/monitor-table-change-with-sqltabledependency#42]
hi good afternoom, morning, evening 
I'm from Mexico so my english is bad, I had the problem with DataType 'text' with sql server 2008 r2 how I can get de data with a String Data in my Class Table Model ???

**Comment by EdmundoCoate** [comment]
Hi ... I forgot to put the Image Column DataType in SQL Server ..... sorry....

**Comment by christiandelbianco** [comment]
IMAGE as well TEXT Sql Server types are not supported. Sorry

**Comment by christiandelbianco** [comment]
Try to use BINARY
