### ISSUE TITLE
not detecting any change in table when deployed on IIS 8 windows server

### ISSUE THREAD

**Issue by umarsolehri** [christiandelbianco/monitor-table-change-with-sqltabledependency#46]
not detecting any change in table when deployed on IIS 8 windows server, I made dependencies on two tables but none of them is working, but working perfectly on localhost

**Comment by christiandelbianco** [comment]
Hi. Deployment is done using a backup database?

**Comment by umarsolehri** [comment]
Backup database?

**Comment by umarsolehri** [comment]
I created database in sql server in windows server, everything is running fine but not detecting any change

**Comment by christiandelbianco** [comment]
Ok. After runnig your application, can you see SqlTableDependency database objects? For example a new trigger on your database table?

**Comment by christiandelbianco** [comment]
Also, which sqlserver version are you usung?

**Comment by christiandelbianco** [comment]
ok...your code is fine.
When you run your application on local host, i suppose you are using a different DB.
In this case, can you try to change the connection string of your local application, pointing to deployed DB?

I ask that, because can be that DB you are using was created from a old SQL Server instance (for example 2008). Even if now it is under SQL 2014 enterprise, it conserve settings that make it not compatible with  SqlTableDependency.

**Comment by christiandelbianco** [comment]
If you run this SQL script on DB (the one used by deployed on IIS 8 windows server)

**SELECT DatabaseProperty('the database name', 'version')
GO**

what is the result you get?

**Comment by christiandelbianco** [comment]
Also, can you run these two scripts?

**SELECT name, compatibility_level from sys.databases WHERE name = 'the database name'
GO

SELECT name, version from master.dbo.sysdatabases where name = 'the database name'
GO**

**Comment by umarsolehri** [comment]
![dbimage](https://user-images.githubusercontent.com/15965524/39058295-d87ccfe6-44d4-11e8-81c1-2d2701d1f753.png)

**Comment by umarsolehri** [comment]
![dbimage](https://user-images.githubusercontent.com/15965524/39058379-1720f7a4-44d5-11e8-8d9b-4dace80870fc.png)

**Comment by umarsolehri** [comment]
thank you for your cooperation
I also searched a lot and my issue solved by just small changing in connection string
<add name="DefaultConnection" connectionString="Data Source=serverName;Initial Catalog=KCMSDb;User Id = username ; Password = password;Integrated Security=True" providerName="System.Data.SqlClient" />

to 

<add name="DefaultConnection" connectionString="Data Source=serverName;Initial Catalog=KCMSDb;User Id = username ; Password = password;" providerName="System.Data.SqlClient" />


or in simple by just removing "Integrated Security=True" from my connection string

**Comment by gandarez** [comment]
It seems to not work with Integrated Authentication
