### ISSUE TITLE
Support .Net Core

### ISSUE THREAD

**Issue by shah-keyur** [christiandelbianco/monitor-table-change-with-sqltabledependency#47]
Hi Christian,

Any possibility that that there is Nuget package with .Net Core?

Doe is support configuring to multiple table to watch instead of Type T . One at a time.

**Comment by christiandelbianco** [comment]
Hi. If you need to Monitor multiple tables, you must use SqlDependency from Microsoft.

**Comment by shah-keyur** [comment]
Hi, Thanks a lot for quick response.

How about support for .Net core ?

Appreciate your help.

Many thanks,

**Comment by christiandelbianco** [comment]
Nuget for .net core is not available. HOWEVER, sqltabledependency code should be compatible for Core. one year ago an italian develorer made changes in order to work with core and those changes are already implemented in version 6.

Current nuget does not work for core applicazions?

**Comment by shah-keyur** [comment]
It does works , absolutely fine.

It just I want to make docker image and host it on Linux.

So want to make sure will it work that way ?

Thanks,

**Comment by christiandelbianco** [comment]
"So want to make sure will it work that way ?"...what do you mean?
As I told you, integration tests are all done on a SQL Server 2008 R2 instance.
So, I would say "yes, it should works".

**Comment by danielthompson** [comment]
It would be very helpful to build this against dotnet core 2.1 and package it suitably for NuGet.
