### ISSUE TITLE
Support for SQL Server 2008 R2

### ISSUE THREAD

**Issue by RollyPeres** [christiandelbianco/monitor-table-change-with-sqltabledependency#48]
Hi Christian,

I see on your repo that the version for SQL Server must be at least 2012.
Can you confirm it does not work on SQL Server 2008 R2?
If it does not work, could you be so kind to detail the reasons behind ?

Kind regards!

**Comment by christiandelbianco** [comment]
Development has been done using 2014. However it works even with 2008 R2

**Comment by RollyPeres** [comment]
I did notice that.
Thanks for your time!

**Comment by christiandelbianco** [comment]
No problem
