### ISSUE TITLE
SqlException Invalid object name

### ISSUE THREAD

**Issue by georgegeo** [christiandelbianco/monitor-table-change-with-sqltabledependency#49]
hi,
On call of Start() i get this error 
Invalid object name 'dbo_Customers_94173d13-e99c-48ad-9084-bdf2cfb80e79'.
Invalid object name 'dbo_Customers_94173d13-e99c-48ad-9084-bdf2cfb80e79'

I followed the working example and im stuck here for days! Please help thanks :)

**Comment by christiandelbianco** [comment]
have you check that those objects are present in your Database?
it is very possible that user specified in connection string has not grant to create TRIGGER, STORED PROCEDURE, QUEUE and CONTRACT

**Comment by georgegeo** [comment]
I have a table called Customers with its class and my database login user has all the permissions and its a db_owner.

**Comment by georgegeo** [comment]
No nothing is created on the tables and service broker.

**Comment by christiandelbianco** [comment]
this is the problem... can you send me your code?

**Comment by georgegeo** [comment]
```
var connectionString = ConfigurationManager.ConnectionStrings["ConnectionString"].ConnectionString;
            SqlClientPermission permission =
 new SqlClientPermission(
 PermissionState.Unrestricted);
            permission.Demand();
           
         
            using (var dep = new TableDependency.SqlClient.SqlTableDependency<Customers>(connectionString))

            {
                dep.OnChanged += dep_OnChanged;
                dep.OnError += dep_OnError;
                dep.Start();
        


            }
```
Please note that its in a windows service application and i run it onStart()

**Comment by christiandelbianco** [comment]
_This problem is in your code_.

As soon as you get out from the using statement, SqlTableDependency is disposed with all Database objects.

If you want to receive notifications, you must keep a live SqlTableDependency  instance.

**Comment by georgegeo** [comment]
oh ok! Can you please provide me a simple example which illustrates this in a service application?

**Comment by christiandelbianco** [comment]
WCF or Windows service?

**Comment by georgegeo** [comment]
Windows Service!

**Comment by georgegeo** [comment]
Ok thank you for all the help!:)
