### ISSUE TITLE
Support for SQL Geometry and Geography change notification

### ISSUE THREAD

**Issue by sevenninety** [christiandelbianco/monitor-table-change-with-sqltabledependency#5]
Hi

I am using sqltabledependency to monitor change in my table and it works nicely apart from one column. It is of type sys.geometry and holds lat/lon points. When I update the column with a new point there is no change notification. I am trying to report on real-time location change.

I wonder if that is something you would consider supporting please?

Thanks

**Comment by christiandelbianco** [comment]
Hi.

sys.geometry  is a not supported column type by SqlTableDependency. 
I am sorry.

**Comment by sevenninety** [comment]
Thanks for the response. I ended up splitting the geometry out into lat and lon columns and then the change is detected.

**Comment by christiandelbianco** [comment]
Good!
Have a nice day.
Bye
