### ISSUE TITLE
Start timeout value when passed triggers onChanged

### ISSUE THREAD

**Issue by georgegeo** [christiandelbianco/monitor-table-change-with-sqltabledependency#57]
When i start an sqltableDependency with no arguments in the Start method (default timeout 120seconds)
The onchanged method fires after 120 seconds.
My question is is this normal functionality? 
Also if i set the timeout to the max, will i get any issues in the longrun? Memory leaks crashing etc...

**Comment by christiandelbianco** [comment]
Hi, not is not normal. This is a bug. Sorry, a stupid mistake done during last update.

**Comment by christiandelbianco** [comment]
FIXED with 7.1.0
