### ISSUE TITLE
'The object '[TABLE_NAME]' does not exist or is invalid for this operation.'

### ISSUE THREAD

**Issue by gandarez** [christiandelbianco/monitor-table-change-with-sqltabledependency#58]
Getting this error when starting SqlTableDepency

> 'The object '[TABLE_NAME]' does not exist or is invalid for this operation.'

```SQL
CREATE TABLE [HangFire].[State](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[JobId] [int] NOT NULL,
	[Name] [nvarchar](20) NOT NULL,
	[Reason] [nvarchar](100) NULL,
	[CreatedAt] [datetime] NOT NULL,
	[Data] [nvarchar](max) NULL,
 CONSTRAINT [PK_HangFire_State] PRIMARY KEY CLUSTERED
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
```

**Comment by christiandelbianco** [comment]
When you have a schema different from dbo, you must use data annotation.
Please see: https://github.com/christiandelbianco/monitor-table-change-with-sqltabledependency/wiki/Use-case:-Code-First-Data-Annotations-to-map-model-with-database-table

**Comment by christiandelbianco** [comment]
7.2.0 Fix this issue

**Comment by christiandelbianco** [comment]
Fix with usage of Database Schema Name as constructor parameter
