### ISSUE TITLE
Every single start it's multiplicating entries

### ISSUE THREAD

**Issue by gandarez** [christiandelbianco/monitor-table-change-with-sqltabledependency#59]
Always I start a SqlTableDependency always it create again new entries in Service Broker. 
Is it a bug? 

![image](https://user-images.githubusercontent.com/782854/39436704-2a2d0764-4c75-11e8-923c-cb027c3e4372.png)

**Comment by christiandelbianco** [comment]
This is normal. SqlDependency from microsoft works in the same way.
Every time you run **SqlTableDependency.Start()**, a new set of DB objects is generated.
