### ISSUE TITLE
ColumnAttribute without name

### ISSUE THREAD

**Issue by ErikvdBurgwal** [christiandelbianco/monitor-table-change-with-sqltabledependency#65]
Hi,
I just updated my project (NuGet) to use v7.2.0. 
My models have some properties that have a ColumnAttribute without Name:

[Column(TypeName = "Date")]
public virtual DateTime InvoiceDate { get; set; }

This generates a null-reference-exception in CheckMapperValidity.

My work-around is to add "Name" in the ColumnAttribute for these fields, but it would be better if the name is not required.

Thanks,
Erik

**Comment by christiandelbianco** [comment]
Fixed in release 7.3.0
