### ISSUE TITLE
includeOldValues: true with multiple rows update

### ISSUE THREAD

**Issue by ErikvdBurgwal** [christiandelbianco/monitor-table-change-with-sqltabledependency#66]
Hi, 
When using the option 'includeOldValues: true', I get an exception when updating more than one row, caused by the SqlTableDependency-trigger; 
Subquery returned more than 1 value. This is not permitted when the subquery follows =, !=, <, <= , >, >= or when the subquery is used as an expression.

I assume it is caused by this statement inside the trigger: 
   BEGIN
            SET @dmlType = 'Update'
		 INSERT INTO @modifiedRecordsTable SELECT [OrderNumber], (SELECT [OrderNumber] FROM DELETED),.......
        END
    

To reproduce, execute a query like 'UPDATE [Order] SET OrderNumber = OrderNumber WHERE 1=1;'

Best regards,
Erik

**Comment by christiandelbianco** [comment]
Thank for detailed info and - moreover - how to reproduce it.
Working on.

**Comment by christiandelbianco** [comment]
FIXED in version 7.3.0
