### ISSUE TITLE
Is there demo for SqlTableDependency used with WebApi or ashx?

### ISSUE THREAD

**Issue by GitOffice** [christiandelbianco/monitor-table-change-with-sqltabledependency#67]
Is there demo for SqlTableDependency used with WebApi or generic handler not with signalR? Thanks in advance.

**Comment by christiandelbianco** [comment]
No, there is not. However, it is very easy to implement: Just create your SqlTableDeoendency instance in Global.asax as and subscribe your code to get notifications. On Application_End event, invoke .Stop on your SqlTableDependency instance
