### ISSUE TITLE
SqlTableDependency.Start Timeout

### ISSUE THREAD

**Issue by nvsoares** [christiandelbianco/monitor-table-change-with-sqltabledependency#68]
Hi
We are using SQLTableDependecy with a very large volume of data and we have the following problem. 
When we create a new Dependency like this:
`SqlTableDependency<Model> Dependency = new SqlTableDependency<Model>(ConnectionString, DataKey);`

we are receiving the following exception:
`Exception thrown: 'System.Data.SqlClient.SqlException' in System.Data.dll
Additional information: Time out expired.`

We checked your code and the constructor never uses the ConnectionString timeout. Is that why the problem occurs? Can u help us?

**Comment by christiandelbianco** [comment]
Hi, seems that you are using a wrong connection string. Is the **Data Source**  in connection string pointing to an existing SQL Server instance?

**Comment by nvsoares** [comment]
Hello. Yes, the connection string is correct and points to an existing sql instance that is online. I am doing more testing to try to find the source of the problem because if restore  database to a backup from a few days ago, it works. The database has not changed except "fake" updates to force batch changes and monitor the behavior of the service and the database itself.

**Comment by christiandelbianco** [comment]
Hi.
One consideration. If you try to use SqlTableDependency DB objects from a
restored DB, it should not work.

*---------------------------------------------------*
*Christian  Del  Bianco*

*---------------------------------------------------**Mobile*: 0041 76 79
65 365
*Mobile*: 0039 347 99 27 897
*Skype*: christian.delbianco
*Email*: christian.delbianco@gmail.com

**Comment by vipatel07** [comment]
Why would the SqlTableDependency not work if it is a Restored Database?
