### ISSUE TITLE
problem when using sql bulk copy

### ISSUE THREAD

**Issue by AshrafGhorabi** [christiandelbianco/monitor-table-change-with-sqltabledependency#69]
Dear sir,

Hope you are well,

i am deleting multiple records then inserting using  sql bulk copy, all change events raised are delete.

problem solved when i set SqlBulkCopyOptions.FireTriggers

Regards

**Comment by christiandelbianco** [comment]
Thanks. I will put your solution in home page (check bottom page)
Thanks.
