### ISSUE TITLE
Slows down access to Table a lot when deleting a lot of rows at once

### ISSUE THREAD

**Issue by werner-1** [christiandelbianco/monitor-table-change-with-sqltabledependency#70]
Installing this on a Table and then deleting a lot of rows at once slows down the delete operation. The slowdown causes operation time-outs.

I suspect it is because every row element is sent through one at a time. I think the broker messages could be operation at a time, which should remove some overhead and reduce the impact on performance.

**Comment by christiandelbianco** [comment]
SqlTableDependency split notification message in multiple QUEUE rows to manage notifications containing VARCHAR(MAX) and BINARY(MAX) type. Queue cannot contain messages with lenght that is > VARCHAR(MAX) + BINARY(MAX). This is the reason why i split a message in multiple rows
