### ISSUE TITLE
Possible to detect change in any column?

### ISSUE THREAD

**Issue by NicksonYap** [christiandelbianco/monitor-table-change-with-sqltabledependency#74]
Hi Christian,

This may be a feature request,
Is there a workaround to allow detecting change of any column of a row,
and then obtain only the required columns of the changed row?

Thanks!

**Comment by NicksonYap** [comment]
Would be very useful to also return the `rowNumber`

**Comment by christiandelbianco** [comment]
rowNumber is retured, is specified in the C# model: check integration test https://github.com/christiandelbianco/monitor-table-change-with-sqltabledependency/blob/master/Tests/TableDependency.SqlClient.IntegrationTest/RowVersionTypeTest.cs

**Comment by christiandelbianco** [comment]
Concerning your initial request "detecting change of any column of a row", simply create e C# model with all properties matching table columns. Then, specify includeOldValue parameter. In this way, the notification will contains new values as well as old values. At this point you can make a manual check to detect which table column has been updated

**Comment by NicksonYap** [comment]
Nice to know rowNumber is returned.

However,
I have a badly designed table with about 30-40 columns.
With includeOldValues, it would be 60-80 message types.

When trying to update a row, the query actually timeout and failed.

Does that have to do with the fact that too large nunber of columns are specified, instead of a simple SELECT *?

**Comment by christiandelbianco** [comment]
mmm...never tested with a table containing so many columns.
Can you send me the SQL script to create it. So i can reproduce it locally on my PC?

**Comment by NicksonYap** [comment]
Not really familiar with SQL Server, hopefully the file attached works
You may need to modify for it to work with your setup
[arscusttable.zip](https://github.com/christiandelbianco/monitor-table-change-with-sqltabledependency/files/2097124/arscusttable.zip)

**Comment by NicksonYap** [comment]
If it helps, this is the class:
[TableClass.zip](https://github.com/christiandelbianco/monitor-table-change-with-sqltabledependency/files/2097139/TableClass.zip)
