### ISSUE TITLE
Conversation handle 00000000-00000 etc. not found

### ISSUE THREAD

**Issue by OriginalDREiD** [christiandelbianco/monitor-table-change-with-sqltabledependency#75]
I have been using SQLDepency for my application for a while and came across yours which looks great for my requirements.

I got the code up and running but one I've started the tabledependency, edits to the table results in the conversation handle 00000000-0000-0000-0000-000000000000 is not found.

If I stop the tabledependency, edits work fine.

Thanks.

**Comment by elclon** [comment]
Hi, I have the same problem! How did you solve it?

**Comment by OriginalDREiD** [comment]
@elclon unable to solve. Hoping @christiandelbianco can help me out.

**Comment by OriginalDREiD** [comment]
Thank you @igitur, moving the block back to the original position resolved the issue for me.

**Comment by igitur** [comment]
I don't think this issue should be closed until @christiandelbianco comments on it.

**Comment by christiandelbianco** [comment]
I immediately  move this.ConversationHandle = this.BeginConversation(sqlCommand); where it was before

**Comment by igitur** [comment]
Great, thanks @christiandelbianco . PS: I discovered this project only last week. Great work!

**Comment by christiandelbianco** [comment]
@igitur As you found the resolution , i will put in Contributors page, if you do not mind

**Comment by igitur** [comment]
> As you found the resolution , i will put in Contributors page, if you do not mind

No problem. I'm planning to submit a PR soon anyway.

**Comment by christiandelbianco** [comment]
Fix in version 7.5.0

**Comment by christiandelbianco** [comment]
@igitur : https://github.com/christiandelbianco/monitor-table-change-with-sqltabledependency/wiki/Contributors

**Comment by OriginalDREiD** [comment]
Thank you, gentlemen.
