### ISSUE TITLE
How to mock SqlTableDepndency integration in unit test

### ISSUE THREAD

**Issue by rupendra-sharma** [christiandelbianco/monitor-table-change-with-sqltabledependency#8]
Hi
I am using SqlTableDepndency in my code to monitor a table. Is there a way to mock SqlTableDepndency in my unit test code or the integration tests are the only way to test the code?
Could you please suggest.

Thanks
Rupendra

**Comment by christiandelbianco** [comment]
Hi, you Can mock implementino the base interfacce or the base class.
