### ISSUE TITLE
No notification after record change

### ISSUE THREAD

**Issue by lapido** [christiandelbianco/monitor-table-change-with-sqltabledependency#80]
Please help.

I'm not receiving a notification change.
The version of my sql server is 2012.

**Comment by christiandelbianco** [comment]
Hi.
First, have a look at :

- Audit record table change requirements
- Note about Compatibility Level and Database Version for tracking record changes

in home page.

Then, if this do sole your issue, send me a zip containing your code.

**Comment by lapido** [comment]
Thanks for your help.
It does not solve the issue.

[DBUpdateService.zip](https://github.com/christiandelbianco/monitor-table-change-with-sqltabledependency/files/2136465/DBUpdateService.zip)

**Comment by christiandelbianco** [comment]
Please check my test here: [https://streamable.com/n1sge](https://streamable.com/n1sge)
As you can see, it works.
Again check db version and credentials for your user

**Comment by lapido** [comment]
Thanks, I will.

**Comment by lapido** [comment]
Is there a way I can debug in order to know where the problem is coming from?

**Comment by christiandelbianco** [comment]
yes: 
remove nuget package reference.
download source core.
include it in your solution
