### ISSUE TITLE
Duplicate *is* in readme.md file

### ISSUE THREAD

**Issue by Nilkamal** [christiandelbianco/monitor-table-change-with-sqltabledependency#81]

**Comment by christiandelbianco** [comment]
Thanks

**Comment by christiandelbianco** [comment]
I do not understand your question...

**Comment by Nilkamal** [comment]
Can i used sql table dependency involving multiple tables by joining left join?

**Comment by christiandelbianco** [comment]
No, sorry

**Comment by christiandelbianco** [comment]
For that you can use Microsoft SqlDependency

**Comment by Nilkamal** [comment]
SqlDepedency also not supported.  I was thinking that SqlTableDependency might support that. Can we work on it?

**Comment by christiandelbianco** [comment]
if you want...

**Comment by Nilkamal** [comment]
Yes please. Guide me.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by christiandelbianco** [comment]
there was a misunderstanding. What i meant was:

 _Can we work on it Table Dependency to make it work?_

 if you want you can try to do.

**Comment by Nilkamal** [comment]
Thats what how i can do it?. Out of box it is not supported right?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by christiandelbianco** [comment]
no, is not supported
