### ISSUE TITLE
Invalid object name 'sys.login_token'

### ISSUE THREAD

**Issue by ericbrunner** [christiandelbianco/monitor-table-change-with-sqltabledependency#84]
Hi,

I get that error on my Azure Sql Server Database on creation of the tableDependency instance.

![image](https://user-images.githubusercontent.com/6480047/42634722-488f7824-85e4-11e8-9b42-e521bb6c0457.png)

Exception:

> {System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'sys.login_token'.
>    at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
>    at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
>    at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
>    at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
>    at System.Data.SqlClient.SqlDataReader.get_MetaData()
>    at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
>    at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
>    at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
>    at TableDependency.SqlClient.SqlTableDependency`1.CheckIfUserHasPermissions(String connectionString)
>    at TableDependency.TableDependency`1..ctor(String connectionString, String tableName, IModelToTableMapper`1 mapper, IUpdateOfModel`1 updateOf, ITableDependencyFilter filter, DmlTriggerType dmlTriggerType, Boolean executeUserPermissionCheck)
>    at SignalRCore.Web.Hubs.InventoryDatabaseSubscription.Configure(String connectionString) in C:\Source\VSTS\SignalR-Core-SqlTableDependency\src\SignalRCore.Web\Hubs\InventoryDatabaseSubscription.cs:line 32
> ClientConnectionId:cdf7e9e8-2617-4775-b22d-65116017cdbe
> Error Number:208,State:1,Class:16}

The sample is from there: https://github.com/vany0114/SignalR-Core-SqlTableDependency 
I reported the issue there , too. Because I don't know he is responsible for that error.

Thanks for your help in advance
best
Eric

**Comment by christiandelbianco** [comment]
Please check:

[https://github.com/christiandelbianco/monitor-table-change-with-sqltabledependency/issues/31](https://github.com/christiandelbianco/monitor-table-change-with-sqltabledependency/issues/31)

**Comment by christiandelbianco** [comment]
https://docs.microsoft.com/en-us/azure/sql-database/sql-database-features

**Comment by ericbrunner** [comment]
Thanks. Maybe the new Azure Sql Database Managed Instance (PREVIEW) can solve it because Service Broker is supported there:
https://docs.microsoft.com/en-us/azure/sql-database/sql-database-features

**Comment by christiandelbianco** [comment]
**sys.login_token** is part of a select used by _SqlTableDependency_ to check if user specified in your connection string has the right grants needed to create database objects (trigger, queue, message type ect...) used for delivering record changes. 

If you are sure that user has enough grants, you can skip this test simply setting the **executeUserPermissionCheck** constructor parameter to **false**.

**Comment by bpnktmpnktcpnkt** [comment]
Ciao Christian,

did I correctly understand you, that setting executeUserPermissionCheck - false will fix the issue?
When I´m right, could you please post the example where to set false instead of true?
Many Thanks in advance.

best regards
bpnkt

**Comment by christiandelbianco** [comment]
well, no, it does not.
if you set executeUserPermissionCheck = false, when start SqlTableDependency does not check if your user has grants expected by SqlTableDependency.

**Comment by smolina74** [comment]
making executeUserPermissionCheck = false I get later a different exception in Azure:
Statement 'CREATE MSGTYPE' is not supported in this version of SQL Server
