### ISSUE TITLE
"Count(*)..." in trigger 

### ISSUE THREAD

**Issue by gromoc** [christiandelbianco/monitor-table-change-with-sqltabledependency#85]
Hi, 
this isn't a issue, its for optimization

I see that this plugin create a trigger in the table that configure. I believe that the "SELECT" statement only execute: "SELECT 1 FROM INSERTED" and not "SELECT * FROM INSERTED", likewise with "SELECT @rowsToProcess = COUNT(1) FROM @modifiedRecordsTable" change the "asterisk" for "1"

The change is not much, it's just an observation

Thank for this plugin 👍

**Comment by christiandelbianco** [comment]
Observation that i appreciate.
In Fact i already applied your suggestion - you can check the source code.
Next release will contains your tips.

Thanks!
