### ISSUE TITLE
Why is the SqlDependency object unable to detect the changes in SQL Server table?

### ISSUE THREAD

**Issue by hunaynrestarted** [christiandelbianco/monitor-table-change-with-sqltabledependency#88]
It's been 3 days that I have been trying to achieve this but couldn't.

I am using the SqlTableDependency nuget package to get notifications if a particular table's cell gets modified. I have enabled the service broker.

I have taken every necessary measure. Upon starting the application it creates a trigger, queue, contract, message type automatically on the table and safely disposes upon closing the app but it never returns the results. The database user has Db_Owner role and everything but still not working. Please help me. I am frustrated and tired of this. It's been 3 days.

I change the values in the edit mode of the table or using an update query.

I am following this link. It has all the necessary steps and also a demo video. https://github.com/christiandelbianco/monitor-table-change-with-sqltabledependency

Code:

```
namespace SqlDependency
{
    class Users
    {
        public string UserName { get; set; }
        public string Password { get; set; }
    }

    class Program
    {
        const string ConnectionString = @"Data Source=(local);Initial Catalog=HimHer; Integrated Security=True";

        static void Main(string[] args)
        {
            using(var dep = new SqlTableDependency<Users>(ConnectionString) )
            {
                dep.OnChanged += Dep_OnChanged;

                dep.Start();

                Console.WriteLine("Press a key to exit");
                Console.ReadKey();

                dep.Stop();
            }

            Console.WriteLine("Waiting For Changes ..... ");
            Console.ReadLine();
        }

        private static void Dep_OnChanged(object sender, RecordChangedEventArgs<Users> e)
        {
            var changedEntity = e.Entity;

            Console.WriteLine("DML operation: " + e.ChangeType);
            Console.WriteLine("ID: " + changedEntity.UserName);
            Console.WriteLine("Name: " + changedEntity.Password);
        }
    }

}
```

**Comment by christiandelbianco** [comment]
I need a copy of your database. Can you remove all tables present in it and send me?

**Comment by hunaynrestarted** [comment]
Sure in a few minutes

**Comment by hunaynrestarted** [comment]
[HimHer.zip](https://github.com/christiandelbianco/monitor-table-change-with-sqltabledependency/files/2238219/HimHer.zip)

**Comment by hunaynrestarted** [comment]
check the database above

**Comment by hunaynrestarted** [comment]
Man, I have spent days on it. but not working

**Comment by hunaynrestarted** [comment]
the above file is in .bak format. I am also going to attach script file.
[himher.zip](https://github.com/christiandelbianco/monitor-table-change-with-sqltabledependency/files/2238225/himher.zip)

**Comment by hunaynrestarted** [comment]
Have you checked ?

**Comment by christiandelbianco** [comment]
May be I was not clear.

I NEED the file .dbms not the script to create it?
Why, because most of times, this database was created time ago using SQL Server 2005 or 2008 (not R2) Instance.

**Comment by christiandelbianco** [comment]
And by the way, have you read "**Note about Compatibility Level and Database Version for tracking record changes**" section?

**Comment by hunaynrestarted** [comment]
Yes, I checked. It's 2012 version.

dbi_version	706	SQL 2012
dbi_createVersion	706	SQL 2012

**Comment by hunaynrestarted** [comment]
Really, I am very very frustrated. It's been 4 days that I am trying but nothing happens,

**Comment by christiandelbianco** [comment]
I need the DB file.

**Comment by hunaynrestarted** [comment]
alright. sharing. .MDF ?

**Comment by christiandelbianco** [comment]
make a .bak file (buckup)

**Comment by hunaynrestarted** [comment]
[HimHer.zip](https://github.com/christiandelbianco/monitor-table-change-with-sqltabledependency/files/2238643/HimHer.zip)

**Comment by hunaynrestarted** [comment]
check this.

**Comment by hunaynrestarted** [comment]
Ok I have already shared the .bak, but sharing again

**Comment by hunaynrestarted** [comment]
[HimHer.zip](https://github.com/christiandelbianco/monitor-table-change-with-sqltabledependency/files/2238645/HimHer.zip)

**Comment by christiandelbianco** [comment]
![capture2](https://user-images.githubusercontent.com/13263017/43365196-365d2ffa-9329-11e8-939c-5a05da9f268e.JPG)
![capture1](https://user-images.githubusercontent.com/13263017/43365197-367b2208-9329-11e8-8420-51b4b45248ea.JPG)

**Comment by christiandelbianco** [comment]
Does not  work

**Comment by hunaynrestarted** [comment]
Because I created it in 2012. maybe that's the reason?

**Comment by hunaynrestarted** [comment]
or add .bak with filename

**Comment by hunaynrestarted** [comment]
[HimHer.zip](https://github.com/christiandelbianco/monitor-table-change-with-sqltabledependency/files/2238655/HimHer.zip)

check this. (I have taken the backup in 2012 version of sql server)

**Comment by hunaynrestarted** [comment]
now?

**Comment by christiandelbianco** [comment]
Restored your DB. Test SqlTableDependency.
Please check the video: [https://streamable.com/no9vw](https://streamable.com/no9vw)

**Comment by hunaynrestarted** [comment]
sure, let me check

**Comment by hunaynrestarted** [comment]
thanks bro but still mine's not working. 

Can you do me a favour and come on teamviewer ? to check my configurations and all. I will be very grateful

**Comment by hunaynrestarted** [comment]
ID: 579 916 281
Pwd: 9129

**Comment by hunaynrestarted** [comment]
Done.

It was only because I haven't been using **sa** as a login. Only I changed my database to **sa** and used that in the connection string. It worked.
