### ISSUE TITLE
Receive also old row values on Table Dependency Changed Event 

### ISSUE THREAD

**Issue by AmmarBashir** [christiandelbianco/monitor-table-change-with-sqltabledependency#9]
Hi christian,
Is this possible to receive old row state with old values and also new row values both via triggers on OnChanged event ? 

Thanks

**Comment by christiandelbianco** [comment]
It is possible, but not in SqlTableDependency free version.

**Comment by AmmarBashir** [comment]
So you do have a paid version, can you redirect me to it?

**Comment by christiandelbianco** [comment]
Please for that I proceed in this way: I get specification from "client" about their requirements and after that I make an extimation. If the "client" accept i make the development just for him. When it is done I deliver the dll as well ad the SOURCE CODE. I also do support for possible errors.

If you need more info, please send me an email to:

christian.delbianco@additiv.ch
