### ISSUE TITLE
Upgrading to latest version 8.5.1 doesn't add the references in the project

### ISSUE THREAD

**Issue by cryo75** [christiandelbianco/monitor-table-change-with-sqltabledependency#91]
I wanted to upgrade from 7.5.0 to 8.5.0 (and also tried 8.5.1) using Nuget. However, after I do so, the references are not added to the project. The package is however listed in my packages.config.

**Comment by christiandelbianco** [comment]
checking

**Comment by christiandelbianco** [comment]
Package 8.5.0 had a problem. This is the reason why is not any more present. However, package 8.5.1 is ok. It contains the needed dll:

![capture](https://user-images.githubusercontent.com/13263017/44569178-d28ae700-a779-11e8-9639-78a5ba611614.JPG)

Can you try to remove SqlTableDependency from your project and than add again?

**Comment by cryo75** [comment]
I removed 7.5.0 from the project and installed 8.5.1. Only TableDependency.SqlClient.dll is added to the references. TableDependency is missing.

**Comment by christiandelbianco** [comment]
This is what you need. Starting from version 8.x only one DLL.
Of course, your old project will not compile any more, because you must adjust using directive.
I suggest you to remove all using TableDependency.xxx statement, and follow Visual Studio suggestion to add new using statements.

**Comment by cryo75** [comment]
Problem solved.
