### ISSUE TITLE
Monitor all columns in runtime defined table by name.

### ISSUE THREAD

**Issue by darlontrofy** [christiandelbianco/monitor-table-change-with-sqltabledependency#97]
I would like to monitor all columns in a table which is passed in dynamically to my method using the SqlTableDependency. Is that possible, since I will not be able to create the model class? I'd like to simply pass in a table name and give it the connection string, and have it monitor that table for changes. Thanks.

**Comment by christiandelbianco** [comment]
I think you can achieve that adding a ROWVERSION column type to your database table.
Then you can use a very easy C# model as:

public class MyModel
{ 
   public byte[] Version { get; set; }
}

Changes done on any table column will be notify to you.
Please check the https://github.com/christiandelbianco/monitor-table-change-with-sqltabledependency/blob/master/TableDependency.SqlClient.Test/RowVersionTypeTest.cs test case as example.

**Comment by darlontrofy** [comment]
I don't have access to modify the structure of the table. I only have the connection string and the table name as parameters.

**Comment by christiandelbianco** [comment]
in this case, you cannot use SqlTableDependency.
