### ISSUE TITLE
Add support for nested mapping

### ISSUE THREAD

**Issue by Flogex** [christiandelbianco/monitor-table-change-with-sqltabledependency#98]
I think it would be nice if we could map properties of a nested object to a table column:
```cs
mapper.AddNestedMapping(obj => obj.NestedObj.Property, "TableColumn");
```

When using this mapping, `NestedObj` would be created with default values and only the particular property would be assigned.

What's your opinion on this?

**Comment by christiandelbianco** [comment]
Hi.
Yes it is a good idea. However, as SqlTableDependency developtment has been close (only mantainance and bug fix are active) your request cannot be taken in consideration.

However, as this is an open source project, you can add this feature and ask for a PULL REQUEST/MERGE on the main branch.

Regards
