### ISSUE TITLE
How to set different header for the group thread request in apache jmeter?

### ISSUE THREAD

**Issue by hunaynrestarted** [christiandelbianco/monitor-table-change-with-sqltabledependency#99]
I want to test concurrency of application, I'm using apache Jmeter for that, the endpoint I'm requesting, needs to have authorization header for authentication, in apache Jmeter HTTP Header Manager i have added a header with the name Authorization with the token value, now lets say I have 5 number of threads (users), when the test runs all the 5 users request with the same authorization token, I want each thread to request with the different token, to simulate the different users and not multiple instances of one user, I hope the question makes sense, How can I make each thread request the api with different token? that is unique header value for each thread's request. Thanks love you guys.

**Comment by christiandelbianco** [comment]
Hi. This question is out-of-scope of SqlTableDependency. Also, I have no experience on apache Jmeter and Java, so i have no idea how i can help you.
